const views=[...document.querySelectorAll("[data-view]")];
const navTabs=[...document.querySelectorAll(".tab")];
const feedback=document.querySelector("#feedback");
const params=new URLSearchParams(window.location.search);
let selectedPlan="Starter";
const planCopy={Starter:{data:"100 Gb +",price:"$39<sup>00</sup>",best:"Best for home",text:"An easy, reliable option for browsing, calls and the everyday devices at home.",fine:"A flexible monthly connection with setup included."},Plus:{data:"300 Gb +",price:"$59<sup>00</sup>",best:"Best for shared spaces",text:"More room for busy homes, video calls and several devices at once.",fine:"A faster monthly connection with priority support."},Studio:{data:"1 Tb +",price:"$89<sup>00</sup>",best:"Best for focused work",text:"High-capacity connection for studios, teams and uninterrupted creative work.",fine:"Our highest capacity connection with dedicated setup."}};
if(params.has("embed")){document.documentElement.classList.add("embed-mode");const fit=()=>document.documentElement.style.setProperty("--embed-scale",String(Math.min(window.innerWidth/390,window.innerHeight / 844)));fit();window.addEventListener("resize",fit)}
function show(name){views.forEach((view)=>{const active=view.dataset.view===name;view.hidden=!active;view.classList.toggle("is-active",active)});navTabs.forEach((tab)=>{const active=tab.dataset.viewTarget===name;tab.classList.toggle("is-active",active);active?tab.setAttribute("aria-current","page"):tab.removeAttribute("aria-current")});feedback.textContent=`${name[0].toUpperCase()+name.slice(1)} is open.`}
document.querySelectorAll("[data-view-target]").forEach((button)=>button.addEventListener("click",()=>show(button.dataset.viewTarget)));
document.querySelectorAll("[data-setting-tab]").forEach((button)=>button.addEventListener("click",()=>{document.querySelectorAll("[data-setting-tab]").forEach((item)=>item.classList.toggle("is-active",item===button));feedback.textContent=`${button.dataset.settingTab} settings selected.`}));
document.querySelectorAll("[data-setting]").forEach((button)=>button.addEventListener("click",()=>{feedback.textContent=`${button.dataset.setting} options opened.`}));
document.querySelector("[data-toggle]").addEventListener("click",(event)=>{const on=event.currentTarget.classList.toggle("is-on");feedback.textContent=`Signal booster ${on?"enabled":"disabled"}.`});
document.querySelectorAll("[data-plan]").forEach((button)=>button.addEventListener("click",()=>{selectedPlan=button.dataset.plan;document.querySelectorAll("[data-plan]").forEach((item)=>{const active=item===button;item.classList.toggle("is-active",active);item.setAttribute("aria-selected",String(active))});const plan=planCopy[selectedPlan];document.querySelector("#planData").textContent=plan.data;document.querySelector("#planPrice").innerHTML=plan.price;document.querySelector("#bestFor").textContent=plan.best;document.querySelector("#planText").textContent=plan.text;document.querySelector("#planFine").textContent=plan.fine;feedback.textContent=`${selectedPlan} plan selected.`}));
document.querySelectorAll("[data-scan]").forEach((button)=>button.addEventListener("click",()=>{const count=document.querySelector("#matchCount");count.textContent="18";document.querySelector("#scanStatus").textContent="18 stable connections matched for your location.";feedback.textContent="Scan complete: 18 stable connections found."}));
document.querySelector("[data-purchase]").addEventListener("click",()=>{document.querySelector("#confirmationText").textContent=`${selectedPlan} has been added to your account. We will keep this signal open for 20 minutes.`;show("confirmation");feedback.textContent=`${selectedPlan} connection reserved.`});
if(params.get("view")==="plans")show("plans");
