export const vocabularyCategories = [
  { id: "all", label: "全部词条", countLabel: "24" },
  { id: "foundation", label: "页面基础", countLabel: "5" },
  { id: "navigation", label: "导航与发现", countLabel: "6" },
  { id: "content", label: "内容展示", countLabel: "5" },
  { id: "controls", label: "控件与表单", countLabel: "3" },
  { id: "feedback", label: "反馈与浮层", countLabel: "4" },
  { id: "visual", label: "视觉与实现", countLabel: "1" },
  { id: "favorites", label: "我的收藏", countLabel: "0" },
];

const image = (src, alt, caption) => ({ src, alt, caption });

export const vocabularyEntries = [
  {
    id: "app-shell",
    name: "应用框架",
    en: "App Shell",
    category: "foundation",
    level: "基础",
    tags: ["结构", "layout-chrome", "响应式"],
    ask: "这个产品的导航和内容区要一直在，页面之间怎么套起来？",
    definition: "应用框架是持续存在的外层结构，把导航、内容区、状态栏和安全区组织成一个可复用的页面骨架。",
    role: "它让用户在不同页面之间移动时，仍然知道自己在哪里，也让各页面共享同一套空间和操作规则。",
    example: image("./assets/cases/news-app/reference-overview.png", "新闻产品的应用框架示例", "新闻案例把顶部导航、内容流和底部入口放在同一套框架里。"),
    anatomy: [["顶部应用栏", "品牌、标题、搜索或页面级操作"], ["主内容区", "当前任务和可滚动内容"], ["导航入口", "桌面侧栏或移动底部标签栏"], ["状态层", "加载、错误、弹窗和全局提示"]],
    variants: [["桌面工作台", "侧栏 + 顶部工具栏，适合高密度任务"], ["移动 App", "顶部安全区 + 内容 + 底部标签栏"], ["沉浸式详情", "弱化导航，让媒体或对象成为焦点"]],
    states: [["默认", "导航和内容都可见，当前入口有选中态"], ["窄屏", "侧栏收起，导航改成横向或底部入口"], ["加载", "保留框架尺寸，用骨架替换内容"]],
    useWhen: ["产品有多个页面或多个主要任务", "需要统一导航、主题和响应式规则"],
    avoidWhen: ["只有一张独立海报或一次性活动页", "页面内容本身就是完整的沉浸式体验"],
    confusedWith: "应用框架不是某一条导航栏；导航只是框架中的一个部件。",
    codeUI: ["语义布局、路由出口、导航、safe-area、焦点顺序"],
    image2: ["照片、产品图、复杂插画放在内容区，不放进框架位图"],
    prompt: "请把产品做成可复用的 App Shell：桌面端使用左侧导航和顶部工具栏，移动端改成顶部安全区与底部标签栏；内容区可滚动，导航保持当前选中态，加载和错误状态不能改变外层尺寸。",
    related: ["top-nav", "bottom-tabs", "responsive"],
    source: "https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/",
  },
  {
    id: "header",
    name: "页头",
    en: "Header",
    category: "foundation",
    level: "基础",
    tags: ["结构", "品牌", "导航"],
    ask: "顶部放 logo、页面名和几个入口，用户一眼知道自己在哪。",
    definition: "页头是页面最上方的品牌与上下文区域，负责建立身份、层级和全局入口。",
    role: "先回答‘这是哪个产品/页面’，再把最常用的全局操作放在用户预期的位置。",
    example: image("./demo/plate-play/mobile-preview.png", "食谱 App 页头示例", "页头用品牌名、个人入口和留白建立页面身份。"),
    anatomy: [["品牌标识", "产品名或 logo，链接回起点"], ["页面上下文", "当前页面标题、面包屑或返回"], ["全局操作", "搜索、主题、账户、更多"], ["响应式折叠", "窄屏时合并成菜单或图标按钮"]],
    variants: [["品牌页头", "突出品牌和一级导航"], ["应用页头", "突出页面标题与返回/更多"], ["透明页头", "叠在首屏媒体上，需确保对比度"]],
    states: [["当前页", "当前入口清晰标记"], ["滚动后", "可吸顶或缩短高度"], ["菜单打开", "焦点进入菜单，背景层级明确"]],
    useWhen: ["网站或产品需要持续的身份与全局入口", "需要和首屏或内容区形成稳定层级"],
    avoidWhen: ["单一任务的极简确认页", "页头会抢走对象详情的视觉焦点"],
    confusedWith: "页头偏品牌和上下文；顶部导航偏链接组织，二者可以组合但职责不同。",
    codeUI: ["header、nav、真实文字、SVG 图标、键盘焦点"],
    image2: ["品牌摄影或插画可作为背景，logo 和导航文字必须用代码"],
    prompt: "请设计一个轻量页头：左侧品牌名，中间显示当前页面上下文，右侧提供搜索与账户入口；图标使用统一 SVG，所有按钮有 aria-label，移动端把次要入口收进菜单。",
    related: ["top-nav", "hero", "app-shell"],
    source: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header",
  },
  {
    id: "hero",
    name: "首屏",
    en: "Hero",
    category: "foundation",
    level: "基础",
    tags: ["官网区块", "image2", "首屏"],
    ask: "网站最上面要有大图和大字，让人马上知道我们是做什么的。",
    definition: "首屏是页面第一个主要视觉区，用最少的信息建立主题、价值和下一步行动。",
    role: "首屏不是把所有内容塞在最上面，而是让用户在几秒内完成理解并知道下一步。",
    example: image("./assets/cases/fashion-shopping-app/hero-screen.png", "时装产品首屏示例", "媒体成为首屏焦点，文案和 CTA 保持为可编辑代码。"),
    anatomy: [["主题标题", "一句话说清产品或页面价值"], ["支持说明", "补足对象、场景或可信度"], ["主行动", "一个清晰的 CTA，避免多个同权重按钮"], ["主视觉", "照片、插画或产品场景，预留文案安全区"]],
    variants: [["媒体主导", "图片或视频占大面积，适合品牌/产品"], ["文字主导", "窄栏标题和 CTA，适合工具入口"], ["双栏拆分", "桌面左右并置，移动端上下堆叠"]],
    states: [["默认", "标题、媒体和 CTA 首屏可见"], ["窄屏", "主视觉裁切保留主体，CTA 不被折叠"], ["减弱动效", "移除自动播放和滚动依赖"]],
    useWhen: ["需要在首屏建立认知和行动", "有足够强的图片、插画或产品展示"],
    avoidWhen: ["用户已经进入高频工作流，不需要品牌叙事", "复杂数据需要立即可比对时"],
    confusedWith: "首屏是一个页面区段；主视觉只是其中的媒体或视觉主体。",
    codeUI: ["标题、正文、CTA、布局、遮罩、响应式裁切"],
    image2: ["摄影、插画、复杂材质和产品场景，禁止烘焙文字与 UI glyph"],
    prompt: "请做一个有明确首屏层级的产品主页：标题和一句说明位于左侧，右侧使用一张无文字、无 logo 的真实场景图；只保留一个主 CTA，移动端改为上下结构并保留下一段内容的可见线索。",
    related: ["cta", "header", "responsive"],
    source: "https://www.nngroup.com/articles/hero-images/",
  },
  {
    id: "cta",
    name: "主按钮 / CTA",
    en: "Call to Action",
    category: "foundation",
    level: "基础",
    tags: ["行动", "code-control", "转化"],
    ask: "给我一个最明显的按钮，用户点它就能开始下一步。",
    definition: "CTA 是页面当前最希望用户完成的主要行动，通常由一个高优先级按钮承载。",
    role: "把理解转成行动，同时通过文案和层级告诉用户点击后会发生什么。",
    example: image("./demo/plate-play/screenshots/detail.png", "食谱详情页主按钮示例", "主按钮使用高对比色，文字直接描述下一步。"),
    anatomy: [["动作文案", "使用开始、保存、继续等动词"], ["视觉层级", "与次要按钮形成明显对比"], ["反馈状态", "按下、加载、成功、失败"], ["触摸区域", "至少 44×44px，文字不被挤压"]],
    variants: [["实心主按钮", "高确定性、高优先级动作"], ["描边次按钮", "可选或返回动作"], ["危险按钮", "删除、退出等需要额外确认的动作"]],
    states: [["默认/悬停", "颜色或阴影变化，不改变布局"], ["加载", "保留按钮宽度，显示进行中"], ["成功/错误", "给出短反馈与恢复路径"]],
    useWhen: ["页面存在一个明确的下一步", "用户需要提交、开始、保存或购买"],
    avoidWhen: ["页面有多个互斥主任务", "按钮文案无法说明点击结果"],
    confusedWith: "CTA 是行动优先级概念，不等同于所有按钮；次级动作也应保留合适层级。",
    codeUI: ["button、状态、键盘焦点、aria-busy、禁用逻辑"],
    image2: ["不把按钮或文字生成进图片；图片只负责情绪和内容"],
    prompt: "请为页面设置一个单一主 CTA，文案使用明确动词；提供默认、hover、focus、loading、success、error 状态，按钮保持稳定尺寸并满足 44px 触摸目标。",
    related: ["button", "hero", "toast"],
    source: "https://www.w3.org/WAI/ARIA/apg/patterns/button/",
  },
  {
    id: "responsive",
    name: "响应式设计",
    en: "Responsive Design",
    category: "foundation",
    level: "进阶",
    tags: ["layout", "移动端", "可用性"],
    ask: "桌面三列到手机要变一列，内容别重叠也别横向滚。",
    definition: "响应式设计让同一套内容根据视口和输入方式调整布局、尺寸、顺序与交互。",
    role: "不是简单缩小桌面页面，而是保留任务优先级并在窄屏重新组织空间。",
    example: image("./assets/cases/news-app/feed-screen.png", "新闻信息流的响应式示例", "信息流在窄屏中保留标题、图片与主要操作，次要信息收起。"),
    anatomy: [["断点策略", "按内容需要而不是设备名称决定"], ["流式容器", "使用 minmax、clamp、max-width"], ["重排规则", "列数、顺序和导航方式变化"], ["触摸目标", "移动端操作区域至少 44px"]],
    variants: [["流式缩放", "字号与间距在范围内变化"], ["结构重排", "桌面侧栏改成底部或抽屉"], ["内容裁剪", "保留主体，隐藏非关键元信息"]],
    states: [["桌面", "多栏与辅助信息可见"], ["平板", "减少列数和侧栏宽度"], ["手机", "单列优先，避免 hover 依赖"]],
    useWhen: ["用户会在不同宽度设备上使用", "内容和操作需要持续可读可点"],
    avoidWhen: ["固定尺寸展览/海报本身就是交付物", "只在单一嵌入容器中展示"],
    confusedWith: "响应式关注结构变化；自适应图片只是其中一个实现手段。",
    codeUI: ["CSS Grid/Flex、container、picture、断点与可访问顺序"],
    image2: ["必要时为移动端单独生成裁切版本，禁止只拉伸桌面图"],
    prompt: "请用内容驱动的响应式布局实现页面：桌面端使用两到三列，移动端改为单列；侧栏折叠为横向筛选或底部入口，所有标题、按钮和图片都不能溢出。",
    related: ["app-shell", "card-grid", "typography"],
    source: "https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design",
  },
  {
    id: "top-nav",
    name: "顶部导航栏",
    en: "Navbar",
    category: "navigation",
    level: "基础",
    tags: ["导航", "code-ui", "全局"],
    ask: "logo、主要栏目和登录入口都放在最上面，还要看得出当前在哪。",
    definition: "顶部导航栏是网站级的主要导航和全局操作区域，通常位于页面顶部并可吸顶。",
    role: "让用户快速在主要栏目之间切换，同时提供搜索、主题或账户入口。",
    example: image("./assets/cases/news-app/headlines-screen.png", "新闻产品顶部导航示例", "顶部导航把品牌、栏目和搜索保持在同一条水平线上。"),
    anatomy: [["品牌入口", "回到首页或产品起点"], ["一级链接", "主要栏目，控制数量"], ["当前标记", "颜色、下划线或背景表达位置"], ["全局操作", "搜索、语言、主题、账户"]],
    variants: [["标准导航", "品牌 + 链接 + 操作"], ["居中品牌", "适合内容和品牌导向网站"], ["透明/覆盖", "适合首屏媒体，但需加强对比度"]],
    states: [["吸顶", "滚动后仍可访问，但不遮挡内容"], ["菜单展开", "移动端抽屉或下拉菜单"], ["当前项", "不仅依赖颜色，补充文字/线条"]],
    useWhen: ["网站有多个主要栏目", "用户需要跨页面快速切换"],
    avoidWhen: ["单任务流程中会分散注意力", "导航项目多到无法扫描"],
    confusedWith: "顶部导航栏组织站点入口；页头可以包含它，也可以只包含页面标题。",
    codeUI: ["nav、a、button、aria-current、移动菜单焦点管理"],
    image2: ["导航中的图片和 logo 不应由生成图承担"],
    prompt: "请做一条克制的顶部导航：左侧品牌，中间 4 个以内的一级入口，右侧搜索与账户；当前入口使用 aria-current 和明显视觉状态，移动端把链接收进可关闭菜单。",
    related: ["header", "app-shell", "bottom-tabs"],
    source: "https://www.w3.org/WAI/ARIA/apg/patterns/menubar/",
  },
  {
    id: "bottom-tabs",
    name: "底部标签栏",
    en: "Bottom Tab Bar",
    category: "navigation",
    level: "基础",
    tags: ["移动端", "导航", "code-icon"],
    ask: "手机底部固定几个入口，首页、收藏和个人资料随时能切换。",
    definition: "底部标签栏是移动端的一级导航容器，固定在屏幕底部并展示少量高频目的地。",
    role: "减少返回成本，让用户在几个核心页面之间快速切换。",
    example: image("./demo/plate-play/mobile-preview.png", "食谱 App 底部导航示例", "底部导航固定在安全区上方，选中项拥有明确状态。"),
    anatomy: [["标签项", "图标 + 短标签，控制在 3–5 项"], ["选中态", "图标、颜色和文字共同表达"], ["安全区", "适配 iOS home indicator"], ["徽标", "只在有未读信息时出现"]],
    variants: [["图标 + 文字", "最容易理解，适合主导航"], ["仅图标", "只适合熟悉用户和极少入口"], ["中心主操作", "把创建或发布作为突出入口"]],
    states: [["选中", "不可只靠颜色，保持文字可见"], ["键盘/读屏", "每项有可访问名称和当前页"], ["滚动", "可保持或隐藏，但必须可恢复"]],
    useWhen: ["移动端有 3–5 个高频一级页面", "用户经常跨页面切换"],
    avoidWhen: ["入口超过 5 个", "页面需要沉浸式全屏操作"],
    confusedWith: "底部标签栏是一级导航；工具栏或操作栏不应该混进来。",
    codeUI: ["nav、button/link、统一 SVG 图标、safe-area-inset-bottom"],
    image2: ["不使用位图图标或生成式导航图"],
    prompt: "请为移动端添加 4 项底部标签栏，固定在 safe-area 上方；每项包含统一线性图标和短标签，当前页使用 aria-current，内容滚动时不能遮挡最后一项。",
    related: ["tabs", "app-shell", "top-nav"],
    source: "https://m3.material.io/components/navigation-bar/overview",
  },
  {
    id: "tabs",
    name: "标签页",
    en: "Tabs",
    category: "navigation",
    level: "基础",
    tags: ["切换", "内容组织", "code-control"],
    ask: "内容太多了，分几个页签，点一下就在同一块区域换内容。",
    definition: "标签页在同一语境中切换互相关联的内容面板，不应被用来隐藏完全不同的任务。",
    role: "降低页面高度和认知负担，让用户在同一上下文比较或浏览内容。",
    example: image("./assets/cases/museum-app/exhibitions-screen.png", "博物馆内容标签页示例", "标签页把展览、收藏和介绍放进同一个内容上下文。"),
    anatomy: [["标签列表", "短标题，顺序表达内容关系"], ["选中指示", "下划线、底色或高对比"], ["面板", "与标签一一对应"], ["键盘行为", "左右键切换，Tab 进入面板"]],
    variants: [["线性标签", "轻量、适合内容阅读"], ["胶囊标签", "适合筛选和视图切换"], ["滚动标签", "窄屏容纳较多同级内容"]],
    states: [["选中", "保持焦点和面板同步"], ["禁用", "说明为什么不可用"], ["加载", "只替换面板，不抖动标签栏"]],
    useWhen: ["同一对象有 2–5 组并列内容", "用户需要在同一语境内来回比较"],
    avoidWhen: ["每个标签都是完全独立的任务", "标签数量多到无法扫描"],
    confusedWith: "Tabs 切换内容面板；分段控件更像切换一个视图模式或筛选值。",
    codeUI: ["button、role=tab、aria-controls、键盘方向键与面板隐藏"],
    image2: ["标签文字与选中态必须由代码渲染"],
    prompt: "请实现一组可访问 Tabs：标签与面板一一对应，支持键盘左右切换和深链接；切换时不重置滚动位置，移动端允许横向滚动但不能出现页面横向溢出。",
    related: ["segmented", "filter-chips", "bottom-tabs"],
    source: "https://www.w3.org/WAI/ARIA/apg/patterns/tabs/",
  },
  {
    id: "segmented",
    name: "分段控件",
    en: "Segmented Control",
    category: "navigation",
    level: "基础",
    tags: ["切换", "视图", "code-control"],
    ask: "就两个或三个模式并排，点哪个就切哪个，像 iPhone 的切换条。",
    definition: "分段控件让用户在少量互斥选项之间切换当前视图或状态。",
    role: "比下拉更快，比标签页更紧凑，适合网格/列表、周/月或浅色/深色等模式。",
    example: image("./demo/fithub/screenshots/00-desktop.png", "健身工作台分段控件示例", "分段控件使用短标签表达互斥的视图模式。"),
    anatomy: [["分段容器", "保持同一组视觉边界"], ["选项", "2–4 个短词，互斥"], ["选中滑块", "表达当前模式，不改变整体宽度"], ["状态反馈", "切换后内容立即同步"]],
    variants: [["文字分段", "最通用"], ["图标 + 文字", "图标提供辅助识别"], ["紧凑分段", "工具栏中的小尺寸视图切换"]],
    states: [["选中", "滑块或底色移动，避免只换文字颜色"], ["禁用", "保持布局，降低对比度"], ["加载", "保留选中项并在面板反馈"]],
    useWhen: ["只有少量互斥模式", "切换后仍在同一页面和同一任务"],
    avoidWhen: ["选项不是互斥的", "每个选项需要长说明或图片"] ,
    confusedWith: "分段控件偏向模式切换；Tabs 偏向内容分组和面板导航。",
    codeUI: ["button、radiogroup、aria-pressed/checked、稳定尺寸"],
    image2: ["不要生成分段控件或选中滑块"],
    prompt: "请使用一个 3 段 Segmented Control 切换数据视图，选中滑块保持同一宽度和高度；为键盘与屏幕阅读器提供 radiogroup 语义，不要把长句塞进选项。",
    related: ["tabs", "filter-chips", "responsive"],
    source: "https://m3.material.io/components/segmented-buttons/overview",
  },
  {
    id: "search",
    name: "搜索框",
    en: "Search",
    category: "navigation",
    level: "基础",
    tags: ["发现", "输入", "code-control"],
    ask: "项目太多了，加个搜索让我按名字或关键词马上找到。",
    definition: "搜索框接收用户的查询，并在本地或远程内容中返回相关结果、建议或无结果状态。",
    role: "把浏览从‘一张张看’变成‘带着意图找’，尤其适合术语、案例、文件和商品目录。",
    example: image("./assets/cases/news-app/discover-screen.png", "内容发现页搜索示例", "搜索与主题筛选并列，结果区负责承接查询反馈。"),
    anatomy: [["输入区", "明确 placeholder 与清除按钮"], ["搜索图标", "辅助识别，不替代可访问名称"], ["建议/历史", "帮助用户快速完成查询"], ["结果状态", "加载、匹配、无结果、错误"]],
    variants: [["即时搜索", "输入后实时筛选，适合本地数据"], ["提交搜索", "按 Enter 或按钮触发，适合远程查询"], ["命令搜索", "支持快捷键和分组结果"]],
    states: [["输入中", "保留查询值，显示清除动作"], ["加载", "显示进行中，不清空输入"], ["无结果", "说明如何修改查询并提供清除"]],
    useWhen: ["条目多且用户有明确关键词", "内容需要跨分类查找"],
    avoidWhen: ["内容少到 5 项以内", "查询结果无法解释或没有恢复路径"],
    confusedWith: "搜索主动查找；筛选标签是在已知集合中缩小范围。",
    codeUI: ["input type=search、debounce、键盘提交、结果 live region"],
    image2: ["搜索图标用代码，不能把输入框烘焙进图片"],
    prompt: "请添加一个可访问的搜索框，支持 Enter 提交、Esc 清空、即时结果和无结果状态；搜索结果按名称、英文名、标签和用户表达匹配，输入值始终保留。",
    related: ["filter-chips", "empty-state", "form"],
    source: "https://www.w3.org/WAI/ARIA/apg/patterns/combobox/",
  },
  {
    id: "filter-chips",
    name: "筛选标签",
    en: "Filter Chips",
    category: "navigation",
    level: "基础",
    tags: ["发现", "筛选", "code-control"],
    ask: "只显示本周、未完成、负责人是我的项目，其他先别看。",
    definition: "筛选标签是紧凑的可选条件，用于快速缩小当前集合或表达已启用的过滤条件。",
    role: "让用户看见‘为什么只剩这些结果’，并允许低成本地打开、关闭和清除条件。",
    example: image("./demo/fithub/screenshots/01-discover.png", "健身发现页筛选标签示例", "筛选标签靠近结果区，选中状态和结果数量一起更新。"),
    anatomy: [["标签文案", "条件短而可扫描"], ["选中态", "颜色 + 勾选或填充"], ["清除动作", "单个移除或一键清空"], ["结果反馈", "数量、空状态或加载"]],
    variants: [["单选筛选", "多个条件只能选一个"], ["多选筛选", "条件可以叠加"], ["可关闭标签", "把已选条件固定在结果顶部"]],
    states: [["默认", "未启用条件保持轻量"], ["选中", "明显但不喧宾夺主"], ["无结果", "保留条件并解释如何放宽"]],
    useWhen: ["结果集合需要快速缩小", "用户需要看到当前条件"],
    avoidWhen: ["条件多且有层级，使用筛选面板更清晰", "筛选逻辑无法用短标签表达"],
    confusedWith: "筛选标签是条件；标签页是内容容器；Badge 只是状态或数量展示。",
    codeUI: ["button/checkbox、pressed 状态、筛选状态管理"],
    image2: ["标签形状和文字由代码渲染"],
    prompt: "请在搜索下方放置可多选筛选标签，标签显示当前条件和结果数量；支持清除单个条件、一键重置和无结果说明，移动端可横向滚动但不造成页面溢出。",
    related: ["search", "tabs", "empty-state"],
    source: "https://m3.material.io/components/chips/overview",
  },
  {
    id: "card",
    name: "卡片",
    en: "Card",
    category: "content",
    level: "基础",
    tags: ["内容", "容器", "image2"],
    ask: "每个商品做成一张卡片，图、名字、价格和操作放在一起，整张能点。",
    definition: "卡片把同一对象的标题、摘要、媒体和相关操作组织成一个边界清楚的内容容器。",
    role: "帮助用户扫读一组对象，同时保留对象级点击和局部操作的边界。",
    example: image("./assets/cases/fashion-shopping-app/catalog-screen.png", "时装目录卡片示例", "商品卡把图片、标题、价格和收藏操作组织在同一对象边界内。"),
    anatomy: [["封面", "图片或媒体，提供快速识别"], ["标题", "对象名称，视觉权重最高"], ["元信息", "价格、作者、状态等短信息"], ["操作区", "收藏、预览或进入详情"]],
    variants: [["基础卡片", "以文字和状态为主"], ["带封面", "媒体是主要识别信息"], ["带操作", "卡片内有独立按钮，需避免误触"]],
    states: [["默认/悬停", "边框或阴影变化，不布局跳动"], ["选中/收藏", "状态可见且能撤销"], ["加载", "骨架形状与最终卡片一致"]],
    useWhen: ["每个对象可以独立浏览", "需要重复展示一组相似对象"],
    avoidWhen: ["内容是连续长文", "每项只有一行文字，列表更紧凑", "把卡片再嵌套卡片"],
    confusedWith: "卡片是对象边界；卡片网格是布局；列表是更高密度的重复结构。",
    codeUI: ["article、链接区域、局部按钮、固定宽高比和 alt"],
    image2: ["产品图、照片、插画和缩略图；不生成卡片文字与按钮"],
    prompt: "请把每个对象做成独立卡片：封面、标题、短摘要和一个局部操作；主区域进入详情，局部按钮不触发主区域跳转；不要嵌套卡片，并固定媒体比例避免加载抖动。",
    related: ["card-grid", "media-tile", "list"],
    source: "https://m3.material.io/components/cards/overview",
  },
  {
    id: "card-grid",
    name: "卡片网格",
    en: "Card Grid",
    category: "content",
    level: "基础",
    tags: ["布局", "重复内容", "responsive"],
    ask: "这些案例排成整齐的格子，屏幕窄了自动变成两列或一列。",
    definition: "卡片网格用二维列和行组织重复对象，并根据可用宽度调整列数和卡片最小尺寸。",
    role: "适合比较和浏览同类对象，空间节奏比信息流更规整。",
    example: image("./assets/cases/museum-app/home-screen.png", "内容卡片网格示例", "网格用统一卡片比例承载多个展览入口。"),
    anatomy: [["网格容器", "定义列数、间距和最大宽度"], ["卡片项", "保持对象边界与一致比例"], ["排序/筛选", "改变结果时保留节奏"], ["响应式断点", "从多列收敛到单列"]],
    variants: [["等宽网格", "适合案例、商品、模板"], ["混合尺寸网格", "突出一两个重点对象"], ["水平滚动网格", "适合移动端相关内容"]],
    states: [["加载", "显示同尺寸骨架"], ["无结果", "网格位置出现下一步"], ["窄屏", "列数下降，卡片不挤压文字"]],
    useWhen: ["对象同质、需要并排比较", "每个对象都有可视化封面"],
    avoidWhen: ["内容顺序和时间关系更重要", "单项信息量太大无法在卡片内读完"],
    confusedWith: "网格是布局方式，不等于卡片；网格也可以承载媒体图块或数据条。",
    codeUI: ["CSS Grid、minmax、gap、容器宽度和焦点顺序"],
    image2: ["每张卡片的封面可用本地图片或 image2 资产"],
    prompt: "请用 CSS Grid 实现卡片网格：桌面端 3 列、窄桌面 2 列、手机 1 列；使用 minmax 和固定媒体比例，卡片内部文字不得溢出，筛选后保持网格节奏。",
    related: ["card", "media-tile", "responsive"],
    source: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout",
  },
  {
    id: "list",
    name: "信息流列表",
    en: "Feed List",
    category: "content",
    level: "基础",
    tags: ["内容", "密度", "时间"],
    ask: "内容一条一条排下来，最新的在上面，扫一眼就能看懂。",
    definition: "信息流列表按时间、相关性或优先级连续排列内容项，强调快速扫描和顺序关系。",
    role: "在有限空间里承载更多对象，比卡片网格更适合标题、状态和时间。",
    example: image("./assets/cases/news-app/feed-screen.png", "新闻信息流列表示例", "信息流用图片、标题和时间建立连续阅读节奏。"),
    anatomy: [["列表项", "每行一个对象，边界清楚"], ["主标题", "承担主要识别信息"], ["辅助元信息", "时间、分类、作者或状态"], ["分页/加载", "追加或分页需保持位置"]],
    variants: [["媒体列表", "左图右文，适合新闻"], ["活动列表", "时间、状态和动作更重要"], ["紧凑列表", "适合后台和设置页"]],
    states: [["未读", "字重或状态点表达"], ["加载更多", "追加时不跳回顶部"], ["错误", "保留已加载内容并提供重试"]],
    useWhen: ["顺序、时间或密度比大图更重要", "对象有较长标题和多条元信息"],
    avoidWhen: ["每个对象都依赖大图识别", "用户需要并排比较多张图片"],
    confusedWith: "信息流强调顺序和密度；卡片强调对象边界和媒体识别。",
    codeUI: ["ul/li、链接、时间语义、加载更多和可访问状态"],
    image2: ["列表缩略图可以使用本地照片/插画，但文字必须是代码"],
    prompt: "请做一个新闻信息流：每项包含缩略图、标题、分类和时间，列表按时间排序；移动端保持标题可读，加载更多使用追加而不是重置列表。",
    related: ["card", "media-tile", "card-grid"],
    source: "https://www.nngroup.com/articles/list-design/",
  },
  {
    id: "media-tile",
    name: "媒体图块",
    en: "Media Tile",
    category: "content",
    level: "基础",
    tags: ["图片", "视频", "image2"],
    ask: "做一组图片或视频图块，图是主角，文字只补充标题和类型。",
    definition: "媒体图块以图片或视频作为主要识别信息，代码文字和操作作为辅助层。",
    role: "让用户通过视觉快速发现内容，适合画廊、作品集、媒体库和探索页。",
    example: image("./assets/cases/museum-app/exhibitions-screen.png", "博物馆媒体图块示例", "媒体图块统一比例裁切，标题和收藏操作保持可访问。"),
    anatomy: [["媒体槽位", "固定比例、object-fit 和加载占位"], ["标签", "类型、时长或状态"], ["标题", "短而可扫描"], ["操作", "播放、收藏或打开详情"]],
    variants: [["网格图块", "适合视觉浏览"], ["瀑布流图块", "保留不同图片高度"], ["视频图块", "必须有 poster、控件和暂停行为"]],
    states: [["加载", "使用同尺寸占位避免跳动"], ["播放", "控件和状态由代码绘制"], ["失败", "显示破图替代和重试"]],
    useWhen: ["图片/视频本身是主要内容", "用户需要先看视觉再决定是否打开"],
    avoidWhen: ["图片只是装饰，文字才是主要任务", "生成图无法保证真实内容或版权"],
    confusedWith: "媒体图块是内容展示角色；UI 图标和导航 glyph 不能用图片图块替代。",
    codeUI: ["img/video、alt/poster、播放/收藏按钮、比例约束"],
    image2: ["摄影、插画、产品抠图、纹理和缩略图可用 image2"],
    prompt: "请构建一个媒体图块网格：所有图片使用本地资产、固定比例和有意义的 alt；不要把标题、按钮、播放图标烘焙进图片，卡片内提供真实可点击控件。",
    related: ["card", "hero", "card-grid"],
    source: "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture",
  },
  {
    id: "detail-panel",
    name: "详情面板",
    en: "Detail Panel",
    category: "content",
    level: "进阶",
    tags: ["检查器", "对象详情", "层级"],
    ask: "点中一个对象后，旁边展开详情，列表还留在原位方便对照。",
    definition: "详情面板在当前页面上下文中展示被选对象的完整信息、状态和相关操作。",
    role: "让用户查看细节而不丢失列表、网格或工作区的上下文。",
    example: image("./assets/cases/museum-app/detail-screen.png", "博物馆详情面板示例", "详情页把媒体、描述、时间和下一步操作放到同一上下文。"),
    anatomy: [["对象摘要", "标题、状态、主媒体"], ["信息分组", "描述、元数据、历史"], ["局部操作", "编辑、收藏、分享或关闭"], ["上下文返回", "保留来源列表或面包屑"]],
    variants: [["右侧检查器", "桌面工作区中保持列表可见"], ["全屏详情", "移动端或复杂对象"], ["内联展开", "简单对象的轻量展开"]],
    states: [["打开/关闭", "可回退，焦点有明确落点"], ["加载", "只替换面板内容"], ["错误", "提供重试和返回列表"]],
    useWhen: ["用户需要对照列表和详情", "对象信息多但不应离开当前任务"],
    avoidWhen: ["详情只有一行文字", "打开后必须完成独立长流程"],
    confusedWith: "详情面板强调上下文；模态框会打断背景任务；抽屉是详情面板的一种承载方式。",
    codeUI: ["aside/dialog、焦点管理、关闭与返回、响应式重排"],
    image2: ["对象媒体、照片和插画；面板内文案/状态由代码"],
    prompt: "请在桌面端用右侧详情面板展示选中对象，保留左侧列表；移动端切换成全屏详情并提供返回按钮；打开、关闭、加载和错误状态都要可恢复。",
    related: ["drawer", "modal", "card"],
    source: "https://m3.material.io/components/dialogs/overview",
  },
  {
    id: "button",
    name: "按钮",
    en: "Button",
    category: "controls",
    level: "基础",
    tags: ["操作", "code-control", "可访问性"],
    ask: "帮我加个按钮，点一下就把内容保存下来。",
    definition: "按钮触发当前页面内的动作，例如提交、保存、打开、切换或删除。",
    role: "按钮应该告诉用户‘会发生一个动作’，而不是伪装成跳转链接。",
    example: image("./demo/plate-play/screenshots/detail.png", "食谱详情按钮示例", "按钮文字使用动作动词，并保留足够触摸面积。"),
    anatomy: [["动作文案", "明确结果，不使用模糊的‘确定’"], ["层级", "主、次要、危险操作的视觉差异"], ["图标", "仅作辅助，不替代文字"], ["状态", "hover、active、focus、disabled、loading"]],
    variants: [["Primary", "当前页面最重要的动作"], ["Secondary", "次要或取消动作"], ["Icon button", "空间紧张时的单一熟悉动作"]],
    states: [["悬停/按下", "反馈及时，不引发布局跳动"], ["聚焦", "高对比 focus ring"], ["禁用/加载", "解释原因或保留进行中状态"]],
    useWhen: ["动作发生在当前页面或当前组件", "需要提交、切换或触发反馈"],
    avoidWhen: ["点击会导航到新页面，优先使用链接", "操作后果危险却没有确认或撤销"],
    confusedWith: "Button 做动作；Link 做导航。外观可以相似，但语义和键盘行为不同。",
    codeUI: ["button type、aria-label、focus-visible、disabled、aria-busy"],
    image2: ["按钮、图标、状态和文字不能生成到图片中"],
    prompt: "请用真实 button 元素实现保存动作，提供主/次级层级和 default、hover、active、focus、disabled、loading、success、error 状态；点击后显示可恢复反馈。",
    related: ["cta", "form", "toast"],
    source: "https://www.w3.org/WAI/ARIA/apg/patterns/button/",
  },
  {
    id: "form",
    name: "输入框与表单",
    en: "Input / Form",
    category: "controls",
    level: "基础",
    tags: ["输入", "校验", "code-control"],
    ask: "做一个注册表单，用户填完信息后可以提交，而且错误要说清楚。",
    definition: "表单把多个输入、说明、校验和提交动作组织成一条可完成的任务路径。",
    role: "降低输入成本，及时发现错误，并让用户知道信息会如何被使用。",
    example: image("./demo/organique-food/screenshots/01-choose.png", "餐食选择表单示例", "输入/选择、说明和下一步操作形成清晰的表单路径。"),
    anatomy: [["标签", "说明字段需要填写什么"], ["控件", "输入、选择、开关等真实表单元素"], ["帮助/错误", "靠近字段，说明修复方式"], ["提交区", "显示可用、加载和结果状态"]],
    variants: [["单列表单", "移动端和新手流程优先"], ["分步表单", "信息多但任务顺序明确"], ["内联编辑", "详情页中少量字段即时修改"]],
    states: [["聚焦", "标签和边框状态清楚"], ["校验错误", "文本 + 颜色说明，不只用红色"], ["提交中", "锁定重复提交并显示进度"]],
    useWhen: ["需要收集或修改结构化信息", "有明确提交、保存或下一步"],
    avoidWhen: ["只需要一个搜索词", "字段太多但没有分组或优先级"],
    confusedWith: "输入框是单个字段；表单是多个字段与提交逻辑组成的任务。",
    codeUI: ["label、input、fieldset、校验、autocomplete、错误关联"],
    image2: ["表单结构、文字和状态必须是代码"],
    prompt: "请实现一列优先的可访问表单：每个字段有 label、帮助文本和错误关联；提交按钮包含 loading/success/error 状态，移动端键盘不会遮挡当前字段。",
    related: ["button", "search", "empty-state"],
    source: "https://www.w3.org/WAI/tutorials/forms/",
  },
  {
    id: "toggle",
    name: "开关",
    en: "Switch",
    category: "controls",
    level: "基础",
    tags: ["二元状态", "设置", "code-control"],
    ask: "像手机设置一样，这个功能一拨就开，再拨就关。",
    definition: "开关表达一个可以立即生效的二元设置，开和关都应该拥有清晰的文字或状态反馈。",
    role: "让用户快速控制持续性偏好，而不必通过提交表单才能知道结果。",
    example: image("./assets/cases/fashion-shopping-app/favorites-screen.png", "收藏设置开关示例", "设置项旁边显示当前状态，开关不是装饰图形。"),
    anatomy: [["标签", "说明被控制的设置"], ["轨道", "表达开/关的容器"], ["滑块", "当前值的视觉位置"], ["反馈", "需要时显示已保存或失败"]],
    variants: [["即时保存", "切换后立即保存"], ["本地偏好", "主题、通知、筛选等"], ["带说明开关", "复杂设置需要补充文本"]],
    states: [["on/off", "不只依赖颜色，提供文字或形状差异"], ["禁用", "说明受其他设置限制"], ["保存失败", "允许重试并保留原状态"]],
    useWhen: ["设置只有开/关两种值", "切换后可以立即生效"],
    avoidWhen: ["需要多个选项", "切换会执行危险动作且没有确认"],
    confusedWith: "开关适合持续设置；Checkbox 更适合表单提交时的多选。",
    codeUI: ["button role=switch 或 input、aria-checked、键盘 Space"],
    image2: ["轨道、滑块和状态都用代码渲染"],
    prompt: "请实现一个可访问开关：标签说明设置，Space 可切换，状态用 aria-checked 与视觉同时表达；切换后显示保存成功或失败，不要让开关尺寸变化。",
    related: ["form", "button", "segmented"],
    source: "https://www.w3.org/WAI/ARIA/apg/patterns/switch/",
  },
  {
    id: "modal",
    name: "模态框",
    en: "Modal",
    category: "feedback",
    level: "进阶",
    tags: ["浮层", "打断", "dialog"],
    ask: "点一下之后中间弹个框，背景变灰，先完成这个任务再回去。",
    definition: "模态框通过遮罩暂时阻断背景交互，把用户注意力集中到一个短任务或确认动作。",
    role: "用于确认、编辑、选择或需要集中注意的短流程，但不应滥用来承载普通详情。",
    example: image("./demo/plate-play/screenshots/detail-generated.png", "食谱详情模态层示例", "模态层强调单一任务，关闭和返回路径要清楚。"),
    anatomy: [["遮罩", "降低背景对比度并阻止点击"], ["标题/说明", "解释任务和后果"], ["内容区", "表单、选择或确认信息"], ["关闭/动作", "Escape、关闭按钮和明确 CTA"]],
    variants: [["确认模态", "删除、退出、覆盖等动作"], ["编辑模态", "少量字段的集中修改"], ["全屏模态", "移动端复杂内容"]],
    states: [["打开", "焦点进入对话框"], ["提交中", "防止重复提交"], ["关闭", "返回触发点或保存后的上下文"]],
    useWhen: ["动作需要确认或短暂集中注意", "背景内容暂时不应操作"],
    avoidWhen: ["只是查看详情，抽屉或内联面板更自然", "表单很长且需要上下文"],
    confusedWith: "模态框会阻断背景；Popover/Tooltip 不阻断；抽屉通常保留更多上下文。",
    codeUI: ["dialog、focus trap、aria-modal、Escape、遮罩与恢复焦点"],
    image2: ["背景媒体可用图片，但对话框文字/控件必须是代码"],
    prompt: "请实现一个可访问 modal：打开后焦点进入对话框，Escape 和关闭按钮可退出，背景不能操作，关闭后焦点回到触发按钮；移动端宽度不溢出。",
    related: ["drawer", "toast", "detail-panel"],
    source: "https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/",
  },
  {
    id: "drawer",
    name: "抽屉",
    en: "Drawer",
    category: "feedback",
    level: "进阶",
    tags: ["浮层", "详情", "响应式"],
    ask: "从右边滑出一块详情，背后的列表还看得见，关掉后回到原来的位置。",
    definition: "抽屉是从屏幕边缘滑入的面板，适合承载详情、筛选或次级导航，同时保留背景上下文。",
    role: "在桌面端避免跳页，在移动端可以转换成底部抽屉或全屏面板。",
    example: image("./assets/cases/museum-app/detail-screen.png", "详情抽屉的内容参考", "抽屉中的对象详情与来源列表保持上下文关系。"),
    anatomy: [["边缘入口", "右侧、左侧或底部出现"], ["遮罩", "可选，决定背景是否可操作"], ["标题/关闭", "说明当前面板和退出方式"], ["内容滚动区", "面板内部独立滚动"]],
    variants: [["右侧抽屉", "桌面详情和筛选"], ["左侧抽屉", "导航或工作区列表"], ["底部抽屉", "移动端操作和筛选"]],
    states: [["打开/关闭", "有明确触发与回退"], ["拖拽", "移动端可拖动但不能替代关闭按钮"], ["错误", "面板保留尺寸并提供重试"]],
    useWhen: ["需要保留列表/背景上下文", "详情或筛选内容比 popover 更丰富"],
    avoidWhen: ["内容只有一句提示", "任务需要完全阻断背景且必须确认"],
    confusedWith: "抽屉强调侧边上下文；模态框强调阻断；Popover 强调触发点附近的短信息。",
    codeUI: ["dialog/aside、focus management、滑入过渡、内部滚动"],
    image2: ["面板中的对象图片可用本地资产，面板 chrome 不能生成"],
    prompt: "请实现一个桌面右侧 Drawer，展示选中对象详情；移动端切换为底部 sheet 或全屏面板；支持 Escape、关闭按钮和点击遮罩，打开后保留来源列表滚动位置。",
    related: ["detail-panel", "modal", "bottom-tabs"],
    source: "https://m3.material.io/components/bottom-sheets/overview",
  },
  {
    id: "toast",
    name: "轻提示",
    en: "Toast",
    category: "feedback",
    level: "基础",
    tags: ["反馈", "状态", "code-status"],
    ask: "角落冒出一句‘已保存’，过两秒自动消失，但用户也能知道结果。",
    definition: "轻提示是短暂、非阻断的操作反馈，告诉用户刚刚发生了什么或下一步可以做什么。",
    role: "提供即时确认，不打断用户继续浏览；持续性或高风险信息应使用更强的反馈。",
    example: image("./demo/fufu-bakery/screenshots/03-member.png", "会员操作反馈示例", "短反馈靠近视线边缘出现，不覆盖主要操作。"),
    anatomy: [["消息", "短句说明结果"], ["状态色", "成功、警告、错误有语义差异"], ["持续时间", "给足阅读时间，不只闪一下"], ["撤销/关闭", "重要操作可提供撤销"]],
    variants: [["成功提示", "保存、复制、收藏完成"], ["错误提示", "请求失败并提供重试"], ["带操作提示", "撤销、查看详情或恢复"]],
    states: [["出现", "不抢焦点但可被读屏感知"], ["堆叠", "限制数量，避免互相覆盖"], ["关闭", "自动消失与手动关闭并存"]],
    useWhen: ["短暂反馈即可，不需要用户停下来处理", "操作结果明确且可继续浏览"],
    avoidWhen: ["错误需要修复", "信息必须持续可见", "反馈会改变数据但没有撤销"] ,
    confusedWith: "Toast 短暂反馈；Alert/Banner 持续存在；Modal 会阻断任务。",
    codeUI: ["role=status/alert、计时、堆叠位置、撤销按钮"],
    image2: ["提示框、文字和图标必须由代码渲染"],
    prompt: "请添加一个不会阻断操作的 toast 系统：成功/错误有不同语义，默认持续 3–5 秒，重要操作提供撤销；使用 aria-live，不覆盖移动端底部导航。",
    related: ["empty-state", "button", "modal"],
    source: "https://www.w3.org/WAI/ARIA/apg/patterns/alert/",
  },
  {
    id: "empty-state",
    name: "空 / 加载 / 错误状态",
    en: "Empty / Loading / Error",
    category: "feedback",
    level: "基础",
    tags: ["状态", "恢复", "image2"],
    ask: "没数据、正在加载或出错时别留白，要告诉用户现在发生了什么和下一步怎么办。",
    definition: "状态设计为内容不可用的时刻提供可读反馈、恢复动作和稳定的空间预期。",
    role: "让‘没有内容’不再像页面坏了，并把等待、失败和首次使用区分开。",
    example: image("./demo/cleanbite-scanner/assets/cleanbite-effect-board.png", "状态反馈视觉示例", "状态区域用插画/媒体增加解释，但关键文字和操作仍由代码承载。"),
    anatomy: [["状态标题", "说清空、加载还是失败"], ["解释", "为什么发生，是否需要等待"], ["下一步", "开始、重试、清除筛选或返回"], ["视觉占位", "骨架、插画或状态图，保持尺寸"]],
    variants: [["首访空状态", "解释价值并提供开始动作"], ["无结果", "保留搜索/筛选条件并指导放宽"], ["错误状态", "说明失败和重试/返回路径"]],
    states: [["加载骨架", "形状接近最终内容"], ["空状态", "不把空白误认为错误"], ["错误", "保留可恢复操作和已加载内容"]],
    useWhen: ["请求或集合可能暂时没有内容", "用户需要知道下一步如何恢复"],
    avoidWhen: ["只用一个 spinner 掩盖长期等待", "错误只显示红色而没有说明"] ,
    confusedWith: "空状态是正常没有内容；错误状态是请求或操作失败；加载状态是尚未得到结果。",
    codeUI: ["状态组件、role=status、重试、骨架尺寸和文案"],
    image2: ["状态插画、照片或复杂纹理可作为 image2 asset，但不生成文字/UI"],
    prompt: "请为列表补齐 loading、empty、no-results、error 和 success 状态；每个状态说明发生了什么并给出下一步，骨架尺寸匹配最终卡片，移动端不产生横向滚动。",
    related: ["search", "toast", "card-grid"],
    source: "https://www.nngroup.com/articles/empty-state-interface-design/",
  },
  {
    id: "typography",
    name: "排版层级",
    en: "Typography",
    category: "visual",
    level: "基础",
    tags: ["视觉", "可读性", "code-text"],
    ask: "标题、正文和提示要分出重点，别让整页文字糊成一片。",
    definition: "排版层级用字体、字号、字重、行高和宽度建立阅读顺序。",
    role: "它决定用户先看什么、读起来累不累，以及 UI 是否显得可信。",
    example: image("./assets/readme/hero.png", "前端三件套排版示例", "标题、说明和代码片段用不同层级组织阅读顺序。"),
    anatomy: [["标题层级", "页面、区段、组件标题"], ["正文", "稳定字号和行高，控制阅读宽度"], ["辅助信息", "标签、时间和说明，不能变成噪点"], ["代码/数字", "使用适合扫描的等宽或数字字形"]],
    variants: [["单一无衬线", "产品和工具 UI 的稳妥选择"], ["衬线标题 + 无衬线正文", "编辑/品牌语境"], ["紧凑数据型", "仪表盘和表格"]],
    states: [["响应式", "字号有上下限，标题可换行"], ["聚焦/选中", "不要只靠字重变化"], ["截断", "只在明确允许时使用省略号"]],
    useWhen: ["页面需要快速扫描或连续阅读", "信息有明显主次关系"],
    avoidWhen: ["用颜色或渐变替代真正层级", "正文小到无法在手机上阅读"],
    confusedWith: "排版层级是视觉规则；标题区/页头是页面结构角色。",
    codeUI: ["真实文本、font-size、line-height、max-width、text-wrap"],
    image2: ["不把可编辑文字烘焙到生成图片"],
    prompt: "请建立清晰的排版 token：页面标题、区段标题、正文、辅助文字和代码各有固定字号与行高；正文保持 16px 左右，移动端长标题可换行，不使用负字距。",
    related: ["header", "card", "responsive"],
    source: "https://www.w3.org/WAI/tips/designing.html",
  },
];

export const vocabularyById = Object.fromEntries(vocabularyEntries.map((entry) => [entry.id, entry]));
