export const repositories = [
  { slug: "Vincentwei1021/video-shotcraft", category: "VIDEO", title: "video-shotcraft", skillName: "video-shotcraft", coverType: "video", coverSrc: "./assets/skills/repositories/vincentwei1021-video-shotcraft-cover.mp4", detailMediaType: "video", detailMediaSrc: "./assets/skills/repositories/vincentwei1021-video-shotcraft-cover.mp4", fallback: "面向产品宣传视频的镜头配方与动态样例库。", focus: "视频叙事 / 动态样例" },
  { slug: "emilkowalski/skills", category: "DESIGN", title: "emilkowalski / skills", coverImage: "./assets/skills/repositories/emilkowalski-skills-cover.png", detailMediaSrc: "./assets/skills/repositories/emilkowalski-skills-cover.png", fallback: "为设计师和工程师准备的一组实用 skills。", focus: "产品设计 / 前端体验" },
  { slug: "pbakaus/impeccable", category: "DESIGN", title: "pbakaus / impeccable", fallback: "帮助 AI 更好理解设计语言与界面质量的 skill。", focus: "设计语言 / UI 品质" },
  { slug: "greensock/GSAP", category: "MOTION", title: "greensock / GSAP", coverType: "video", coverSrc: "./assets/skills/repositories/greensock-gsap-cover.mp4", detailMediaType: "video", detailMediaSrc: "./assets/skills/repositories/greensock-gsap-cover.mp4", extraTags: { zh: ["强推", "动效"], en: ["Strong pick", "Motion"] }, fallback: "现代 Web 动画的成熟工具与生态。", focus: "动效系统 / 交互反馈" },
  { slug: "Leonxlnx/taste-skill", category: "DESIGN", title: "Leonxlnx / taste-skill", coverImage: "./assets/skills/repositories/leonxlnx-taste-skill-cover.png", detailMediaSrc: "./assets/skills/repositories/leonxlnx-taste-skill-detail.png", fallback: "让 AI 避免生成无聊、通用、模板化界面的设计品味 skill。", focus: "去模板感 / 视觉判断" },
  { slug: "mattpocock/skills", category: "ENGINEERING", title: "mattpocock / skills", coverType: "video", coverSrc: "./assets/skills/repositories/mattpocock-skills-cover.mp4", coverImage: "./assets/skills/repositories/mattpocock-skills-cover.png", detailMediaType: "video", detailMediaSrc: "./assets/skills/repositories/mattpocock-skills-cover.mp4", fallback: "面向真实工程工作的可复用 agent skills。", focus: "工程工作流 / Agent" },
  { slug: "anthropics/skills", category: "DESIGN", title: "anthropics / skills", coverImage: "./assets/skills/repositories/anthropics-skills-cover.png", detailMediaSrc: "./assets/skills/repositories/anthropics-skills-cover.png", fallback: "包含 frontend-design 等面向真实创作任务的官方 skill 集合。", focus: "界面构建 / 创作工作流" },
  { slug: "vercel-labs/agent-skills", category: "FRONTEND", title: "vercel-labs / agent-skills", coverImage: "./assets/skills/repositories/vercel-labs-agent-skills-cover.svg", detailMediaSrc: "./assets/skills/repositories/vercel-labs-agent-skills-cover.svg", fallback: "面向 Web 产品的设计规范、React 模式与前端质量检查。", focus: "Web 规范 / React 质量" },
  { slug: "nexu-io/open-design", category: "AI DESIGN", title: "nexu-io / open-design", coverImage: "./assets/skills/repositories/nexu-io-open-design-cover.png", detailMediaSrc: "./assets/skills/repositories/nexu-io-open-design-cover.png", fallback: "面向 AI 设计生成的开放式工作台，支持 UI Mockup、线框、移动应用、文档、视频等多类型创作入口，并围绕设计系统和工作目录组织产出。", focus: "AI 设计工作台 / UI Mockup / 多类型生成" },
  { slug: "vercel-labs/design-systems-to-agent-skills", category: "SYSTEM", title: "Design Systems → Agent Skills", fallback: "把已有设计系统转成 Agent Skill 的方法库，强调访谈、源码事实提取、使用模式分析和可执行规范沉淀。", focus: "Design System 转 Skill / 规范提取" },
  { slug: "Subhan-code/Amicro--Micro-transitions-", category: "MOTION", title: "Subhan-code / Amicro", coverImage: "./assets/skills/repositories/subhan-code-amicro-micro-transitions-cover.svg", detailMediaSrc: "./assets/skills/repositories/subhan-code-amicro-micro-transitions-cover.svg", fallback: "面向 React 的微交互、转场动画与卡片布局集合，强调平滑节奏与简洁反馈。", focus: "Micro transitions / Motion / Card layouts" },
  { slug: "weareoxd/design-skill-generator", category: "AI DESIGN", title: "Design Skill Generator", fallback: "从截图或 Figma URL 自动生成 SKILL.md 与 tokens.css，提取颜色、字体、间距、组件模式、导航、图标与反模式。", focus: "截图转 Skill / Figma / Tokens" },
  { slug: "nolly-studio/agent-skills", category: "SYSTEM", title: "Nolly Studio / design-md", fallback: "基于真实项目代码生成 DESIGN.md 设计语言契约，帮助 Agent 明确字体、颜色、圆角、阴影、动效和 Token 用法。", focus: "DESIGN.md / 设计语言契约" },
  { slug: "nextlevelbuilder/ui-ux-pro-max-skill", category: "PRESENTATION", title: "ui-ux-pro-max", coverImage: "./assets/skills/repositories/nextlevelbuilder-ui-ux-pro-max-skill-cover.png", detailMediaSrc: "./assets/skills/repositories/nextlevelbuilder-ui-ux-pro-max-skill-cover.png", fallback: "把复杂业务数据转成带交互的 SVG 图表、UI 级看板与高保真演示页面。", focus: "数据复盘 / 产品评审 / 技术展示" },
  { slug: "motiondivision/motion", category: "MOTION", title: "motiondivision / motion", fallback: "为 React、Vue 和原生 Web 提供流畅、可组合的界面动效。", focus: "组件动效 / 微交互" },
  { slug: "radix-ui/primitives", category: "A11Y", title: "radix-ui / primitives", coverType: "video", coverSrc: "./assets/skills/repositories/radix-ui-primitives-cover.mp4", detailMediaType: "video", detailMediaSrc: "./assets/skills/repositories/radix-ui-primitives-cover.mp4", fallback: "无样式、可访问、可组合的 UI 原语，适合建立可靠组件层。", focus: "无障碍 / 组件原语" },
  { slug: "shadcn-ui/ui", category: "FRONTEND", title: "shadcn-ui / ui", coverType: "video", coverSrc: "./assets/skills/repositories/shadcn-ui-ui-cover.mp4", detailMediaType: "video", detailMediaSrc: "./assets/skills/repositories/shadcn-ui-ui-cover.mp4", fallback: "把可复制、可定制的 React 组件直接带进项目，适合快速建立高质量界面系统。", focus: "组件库 / Tailwind / 设计系统" },
  { slug: "wshobson/agents-tailwind-design-system", category: "SYSTEM", title: "Tailwind Design System", fallback: "来自 wshobson/agents 的 Tailwind CSS v4 设计系统 Skill，覆盖 CSS-first 配置、设计 Token、组件变体、响应式模式、暗色模式和可访问性。", focus: "Tailwind v4 / Design Tokens / 组件库" },
  { slug: "tailwindlabs/headlessui", category: "A11Y", title: "tailwindlabs / headlessui", coverType: "video", coverSrc: "./assets/skills/repositories/tailwindlabs-headlessui-cover.mp4", detailMediaType: "video", detailMediaSrc: "./assets/skills/repositories/tailwindlabs-headlessui-cover.mp4", fallback: "为 Tailwind 设计的无样式交互组件，覆盖菜单、弹窗和列表等模式。", focus: "交互模式 / 可访问性" },
  { slug: "twostraws/SwiftUI-Agent-Skill", category: "FRONTEND", title: "SwiftUI Agent Skill", fallback: "面向 Claude Code、Codex 等 AI Coding Assistant 的 SwiftUI Skill，帮助生成更现代、更简洁的 SwiftUI，覆盖导航、布局、动画、状态管理、VoiceOver、性能和弃用 API。", focus: "SwiftUI / iOS / AI Coding" },
  { slug: "lucide-icons/lucide", category: "SYSTEM", title: "lucide-icons / lucide", coverImage: "./assets/skills/repositories/lucide-icons-lucide-cover.png", detailMediaSrc: "./assets/skills/repositories/lucide-icons-lucide-cover.png", fallback: "清晰、可定制的开源图标系统，适合统一产品中的图标语言。", focus: "图标系统 / 视觉一致性" },
  { slug: "pmndrs/react-three-fiber", category: "3D", title: "pmndrs / react-three-fiber", coverType: "video", coverSrc: "./assets/skills/repositories/pmndrs-react-three-fiber-cover.mp4", detailMediaType: "video", detailMediaSrc: "./assets/skills/repositories/pmndrs-react-three-fiber-cover.mp4", fallback: "在 React 中构建 3D 体验的声明式渲染工具。", focus: "3D 交互 / 空间体验" },
  { slug: "ahujasid/blender-mcp", category: "3D", title: "ahujasid / blender-mcp", coverImage: "./assets/skills/repositories/ahujasid-blender-mcp-cover.png", detailMediaSrc: "./assets/skills/repositories/ahujasid-blender-mcp-cover.png", fallback: "把 Blender 接入 MCP，让 AI Agent 可以通过自然语言控制 Blender、创建模型、调整场景、材质和渲染流程。", focus: "Blender / MCP / 3D Agent" },
  { slug: "storybookjs/storybook", category: "SYSTEM", title: "storybookjs / storybook", fallback: "用于开发、测试和记录 UI 组件的工作台。", focus: "组件文档 / 设计协作" },
  { slug: "google-labs-code/stitch-skills", category: "AI DESIGN", title: "google-labs-code / stitch-skills", fallback: "为 Google Stitch MCP 准备的 Agent Skill 集合，覆盖从界面生成到迭代的工作流。", focus: "界面生成 / MCP 工作流" },
  { slug: "figma/mcp-server-guide", category: "AI DESIGN", title: "Figma MCP Server Guide", coverImage: "./assets/skills/repositories/figma-mcp-server-guide-cover.png", detailMediaSrc: "./assets/skills/repositories/figma-mcp-server-guide-cover.png", fallback: "Figma 官方 MCP 连接指南与客户端目录，把 Figma 设计上下文接入 Codex、Claude Code、Cursor 等 Agent 工具。", focus: "Figma MCP / 设计上下文 / Agent 工具" },
  { slug: "bergside/awesome-design-skills", category: "DIRECTORY", title: "bergside / awesome-design-skills", coverType: "video", coverSrc: "./assets/skills/repositories/bergside-awesome-design-skills-cover.mp4", detailMediaType: "video", detailMediaSrc: "./assets/skills/repositories/bergside-awesome-design-skills-cover.mp4", fallback: "整理大量 DESIGN.md 与 SKILL.md 设计能力文件的开放目录。", focus: "设计资源 / Skill 发现" },
  { slug: "gztchan/awesome-design", category: "DIRECTORY", title: "gztchan / awesome-design", fallback: "面向 UI/UX 设计师的高质量资源与工具清单，覆盖图库、图标、色彩、字体、原型、样机、用户测试、教程与社区等日常设计素材。", focus: "设计资源 / 工具索引 / UI/UX 日常" },
  { slug: "magnus919/agent-skills", category: "UX", title: "Product Design & UX", fallback: "面向产品体验的 Agent Skill，覆盖信息架构、任务流、状态恢复、交互模式选择、可用性检查和工程交付说明。", focus: "IA / Task Flow / UX 行为" },
  { slug: "sergekostenchuk/ui-ux-agent-skill-system", category: "FRONTEND", title: "Web App UI Skill", fallback: "专注 Dashboard、Admin、CRM、设置页、表格和筛选器等真实产品 UI，并覆盖 loading、empty、error、disabled、focus、selected、submitting、success 等状态。", focus: "Web App UI / 状态补全 / 后台界面" },
  { slug: "content-designer/ux-writing-skill", category: "UX", title: "UX Writing Skill", fallback: "系统化处理界面文案，包括按钮标签、错误提示、空状态、引导、校验、通知与 Voice & Tone，让产品语言更一致。", focus: "界面文案 / 空状态 / 错误提示" },
  { slug: "Community-Access/accessibility-agents", category: "A11Y", title: "Accessibility Agents", fallback: "提供面向 HTML、JSX、CSS、React 等 UI 的无障碍审查能力，适合在交付前做最终 A11y Audit。", focus: "A11y Audit / HTML / React" },
  { slug: "skydashnet/material-design-3-ui-skill", category: "SYSTEM", title: "Material Design 3 UI Skill", fallback: "围绕 Google Material Design 3 / Material You 的 UI Skill，覆盖语义 Token、自适应布局、可折叠设备、无障碍、动效、导航、表单与字体等模块。", focus: "Material 3 / Semantic Tokens / Adaptive UI" },
  { slug: "wenkang-deepblue/frontend-design", category: "AI DESIGN", title: "frontend-design", fallback: "生成可交互 HTML Preview，让设计师像 DevTools 一样点击元素、调整 Token、写评论，再把修改整理成结构化 Prompt 交回 Claude Code 或 Codex。", focus: "可交互预览 / 设计调整 / Prompt 回传" },
  { slug: "SeanJ1ang/design-judge-skills", category: "REVIEW", title: "SeanJ1ang / design-judge-skills", fallback: "帮助 AI 从视觉质量、信息层级和完成度角度审查界面。", focus: "设计评审 / 质量检查" },
  { slug: "ConardLi/garden-skills", category: "DESIGN", title: "ConardLi / garden-skills", fallback: "面向 AI 产品开发的多类可复用 skills，包含界面与体验工作流。", focus: "产品开发 / 复用能力" },
  { slug: "Owl-Listener/designer-skills", category: "DESIGN", title: "Owl-Listener / designer-skills", coverImage: "./assets/skills/repositories/owl-listener-designer-skills-cover.svg", detailMediaSrc: "./assets/skills/repositories/owl-listener-designer-skills-cover.svg", fallback: "面向设计任务的轻量 skill 集合，适合补充日常界面决策。", focus: "日常设计 / 决策辅助" },
  { slug: "superdesigndev/superdesign-skill", category: "AI DESIGN", title: "superdesigndev / superdesign-skill", fallback: "把设计思考、视觉方向和前端落地连接起来的设计 skill。", focus: "设计思考 / 前端落地" },
  { slug: "mistyhx/frontend-design-audit", category: "REVIEW", title: "mistyhx / frontend-design-audit", fallback: "面向前端页面的设计审计与改进检查清单。", focus: "页面审计 / 改进建议" },
  { slug: "plugin87/ux-ui-agent-skills", category: "UX", title: "plugin87 / ux-ui-agent-skills", fallback: "专注 UX/UI 任务的 Agent Skills 集合，覆盖界面体验与产品设计相关工作。", focus: "UX/UI 设计 / Agent 工作流" },
  { slug: "ZeroZ-lab/cc-design", category: "DESIGN", title: "ZeroZ-lab / cc-design", fallback: "面向 Claude Code 的设计插件与参考资料，包含设计红旗和插件发布工作流。", focus: "设计规范 / Claude Code" },
  { slug: "JimLiu/baoyu-design", category: "SYSTEM", title: "JimLiu / baoyu-design", coverImage: "./assets/skills/repositories/jimliu-baoyu-design-cover.png", detailMediaSrc: "./assets/skills/repositories/jimliu-baoyu-design-cover.png", fallback: "围绕设计系统创建、Figma 导入和实验工作流组织的一套设计能力。", focus: "设计系统 / Figma 导入" },
  { slug: "scottstts/Threejs-Awesome-Graphics-Agent-Skills", category: "3D", title: "scottstts / Threejs-Awesome-Graphics-Agent-Skills", fallback: "面向 Three.js 与图形创作的 Agent Skills 集合，适合补充 3D 和交互视觉能力。", focus: "Three.js / 图形 Agent" },
  { slug: "Owl-Listener/ai-design-skills", category: "DIRECTORY", title: "Owl-Listener / ai-design-skills", fallback: "整理 AI 设计能力和扩展入口的开源集合，适合继续发现跨模型的设计工作流。", focus: "AI 设计 / Skill 发现" },
  { slug: "hugohe3/ppt-master", category: "PRESENTATION", title: "ppt-master", coverType: "video", coverSrc: "./assets/skills/repositories/hugohe3-ppt-master-cover.mp4", detailMediaType: "video", detailMediaSrc: "./assets/skills/repositories/hugohe3-ppt-master-cover.mp4", fallback: "直接输出带完整图层与文字框的原生可编辑 PPTX，便于改字、换图和正式交付。", focus: "职场汇报 / 客户提案 / 可编辑交付" },
  { slug: "zarazhangrui/frontend-slides", category: "PRESENTATION", title: "frontend-slides", coverImage: "./assets/skills/repositories/zarazhangrui-frontend-slides-cover.png", detailMediaSrc: "./assets/skills/repositories/zarazhangrui-frontend-slides-cover.png", fallback: "生成高完成度、零依赖的单文件 HTML 演示，浏览器双击即可开始展示。", focus: "在线演示 / 远程分享 / 交互展示" },
  { slug: "op7418/guizang-ppt-skill", category: "PRESENTATION", title: "guizang-ppt-skill", coverImage: "./assets/skills/repositories/op7418-guizang-ppt-skill-cover.png", detailMediaSrc: "./assets/skills/repositories/op7418-guizang-ppt-skill-cover.png", fallback: "以杂志风和瑞士国际主义建立画册级、海报级演示视觉。", focus: "产品发布会 / 主题演讲 / 品牌展示" },
  { slug: "alchaincyf/huashu-design", category: "PRESENTATION", title: "huashu-design", coverImage: "./assets/skills/repositories/alchaincyf-huashu-design-cover.gif", detailMediaSrc: "./assets/skills/repositories/alchaincyf-huashu-design-cover.gif", fallback: "结合细腻 HTML 动效与可编辑 PPTX 导出，适合复杂设计规范与多格式输出。", focus: "交互原型 / 设计团队 / 混合输出" },
  { slug: "lewislulu/html-ppt-skill", category: "PRESENTATION", title: "html-ppt-skill", coverImage: "./assets/skills/repositories/lewislulu-html-ppt-skill.jpg", detailMediaSrc: "./assets/skills/repositories/lewislulu-html-ppt-skill.jpg", fallback: "提供倒计时、逐字稿提词器、双屏演讲者视图与丰富主题。", focus: "答辩 / 路演 / 提词演讲" },
  { slug: "MiniMax-AI/skills", category: "PRESENTATION", title: "MiniMax-pptx", fallback: "将会议记录或 Markdown 大纲快速转成结构化、可编辑的 PPTX 草稿。", focus: "内部对齐 / 临时出稿 / 大纲可视化" },
  { slug: "ningzimu/codex-ppt", category: "PRESENTATION", title: "codex-ppt", fallback: "以强封面感和海报级单页张力生成视觉语言统一的图片流 PPT。", focus: "社媒切片 / 视觉演讲 / 冲击力开场" },
  { slug: "ningzimu/image-to-editable-ppt-skill", category: "PRESENTATION", title: "image-to-editable-ppt-skill", coverImage: "./assets/skills/repositories/ningzimu-image-to-editable-ppt-skill-cover.png", detailMediaSrc: "./assets/skills/repositories/ningzimu-image-to-editable-ppt-skill-cover.png", fallback: "把图片、PDF 或图片版 PPTX 通过多 Agent 视觉重建成可编辑 PPTX，并支持按需 imagegen 与 OCR 文字校正。", focus: "图片转 PPT / 可编辑 PPTX / OCR 校正" },
  { slug: "ryanbbrown/revealjs-skill", category: "PRESENTATION", title: "revealjs-skill", fallback: "用 Markdown 驱动代码高亮与二维嵌套导航，适合开发者演示。", focus: "技术架构 / 开发者大会 / 开源宣讲" }
];

export const repositoriesEn = [
  { fallback: "An AI video skill with shot recipes and motion examples for product films.", focus: "Video storytelling / motion examples" },
  { fallback: "A practical collection of skills for designers and engineers.", focus: "Product design / frontend experience" },
  { fallback: "A skill that helps AI understand design language and interface quality.", focus: "Design language / UI quality" },
  { fallback: "A mature toolkit and ecosystem for modern Web animation.", focus: "Motion systems / interaction feedback" },
  { fallback: "A design-taste skill that helps AI avoid bland, generic, templated interfaces.", focus: "Less templated / visual judgment" },
  { fallback: "Reusable agent skills for real-world engineering work.", focus: "Engineering workflow / Agent" },
  { fallback: "An official collection of skills for real creative tasks, including frontend-design.", focus: "Interface building / creative workflow" },
  { fallback: "Design guidelines, React patterns and frontend quality checks for Web products.", focus: "Web guidelines / React quality" },
  { fallback: "An open AI design workspace for UI mockups, wireframes, mobile apps, documents and video-oriented creation, organized around design systems and working directories.", focus: "AI design workspace / UI mockups / multi-format generation" },
  { fallback: "A process for transforming an existing design system into an Agent Skill through interviews, source-code fact extraction, usage-pattern analysis and executable guidelines.", focus: "Design system to Skill / guideline extraction" },
  { fallback: "A React micro-interactions, transitions and card-layout collection focused on smooth rhythm and lightweight feedback.", focus: "Micro transitions / Motion / Card layouts" },
  { fallback: "Turns screenshots or Figma URLs into SKILL.md and tokens.css by extracting colors, typography, spacing, component patterns, navigation, icons and anti-patterns.", focus: "Screenshot to Skill / Figma / tokens" },
  { fallback: "Generates a project-level DESIGN.md design-language contract from real code so agents understand typography, color, radii, shadows, motion and token usage.", focus: "DESIGN.md / design-language contract" },
  { fallback: "Turns complex business data into interactive SVG charts, UI-grade dashboards and high-fidelity presentations.", focus: "Data reviews / product critique / technical demos" },
  { fallback: "Smooth, composable interface motion for React, Vue and the Web platform.", focus: "Component motion / micro-interactions" },
  { fallback: "Unstyled, accessible and composable UI primitives for a dependable component layer.", focus: "Accessibility / primitives" },
  { fallback: "Copyable, customizable React components for building high-quality interface systems quickly.", focus: "Component library / Tailwind / design systems" },
  { fallback: "A Tailwind CSS v4 design-system skill from wshobson/agents covering CSS-first configuration, design tokens, component variants, responsive patterns, dark mode and accessibility.", focus: "Tailwind v4 / design tokens / component libraries" },
  { fallback: "Unstyled accessible interaction components designed for Tailwind projects.", focus: "Interaction patterns / accessibility" },
  { fallback: "A SwiftUI skill for Claude Code, Codex and other AI coding assistants, helping them write more modern and simpler SwiftUI across navigation, layout, animation, state management, VoiceOver, performance and deprecated APIs.", focus: "SwiftUI / iOS / AI coding" },
  { fallback: "A clear, customizable open-source icon system for consistent product language.", focus: "Icon systems / visual consistency" },
  { fallback: "A declarative renderer for building 3D experiences in React.", focus: "3D interaction / spatial experience" },
  { fallback: "Connects Blender to MCP so AI agents can control Blender with natural language, create models, adjust scenes, materials and rendering workflows.", focus: "Blender / MCP / 3D agents" },
  { fallback: "A workbench for developing, testing and documenting UI components.", focus: "Component docs / design collaboration" },
  { fallback: "Agent Skills for the Google Stitch MCP server, covering interface generation and iteration workflows.", focus: "Interface generation / MCP workflow" },
  { fallback: "Figma's official MCP connection guide and client catalog for bringing Figma design context into Codex, Claude Code, Cursor and other agentic tools.", focus: "Figma MCP / design context / agent tools" },
  { fallback: "An open directory of DESIGN.md and SKILL.md files for discovering design capabilities.", focus: "Design resources / skill discovery" },
  { fallback: "A curated list of high-quality resources and tools for UI/UX designers, covering stock, icons, color, typography, prototyping, mockups, user testing, tutorials and communities.", focus: "Design resources / tool index / UI/UX practice" },
  { fallback: "An agent skill for product experience work, covering information architecture, task flows, state recovery, interaction-pattern choices, usability checks and engineering handoff.", focus: "IA / task flows / UX behavior" },
  { fallback: "A web-app UI skill for dashboards, admin tools, CRM, settings, tables and filters, with coverage for loading, empty, error, disabled, focus, selected, submitting and success states.", focus: "Web app UI / state coverage / admin interfaces" },
  { fallback: "Systematic UX writing for button labels, errors, empty states, onboarding, validation, notifications and voice and tone consistency.", focus: "Interface copy / empty states / errors" },
  { fallback: "Accessibility audit skills for HTML, JSX, CSS, React and related UI work, useful as a final A11y review before shipping.", focus: "A11y audit / HTML / React" },
  { fallback: "A Material Design 3 / Material You UI skill covering semantic tokens, adaptive layouts, foldables, accessibility, motion, navigation, forms and typography.", focus: "Material 3 / semantic tokens / adaptive UI" },
  { fallback: "Creates an interactive HTML preview where designers can click elements, adjust tokens and leave comments, then send a structured prompt back to Claude Code or Codex.", focus: "Interactive preview / design tweaks / prompt handoff" },
  { fallback: "Helps AI review interface quality, hierarchy and finish from a visual-design perspective.", focus: "Design review / quality checks" },
  { fallback: "Reusable skills for AI product development, including interface and experience workflows.", focus: "Product development / reusable skills" },
  { fallback: "A lightweight collection of skills for everyday interface decisions and design tasks.", focus: "Daily design / decision support" },
  { fallback: "A design skill that connects design thinking, visual direction and frontend execution.", focus: "Design thinking / frontend craft" },
  { fallback: "A design-audit checklist for reviewing and improving frontend pages.", focus: "Page audits / improvement ideas" },
  { fallback: "A collection of agent skills for UX/UI tasks, covering interface experience and product-design work.", focus: "UX/UI design / Agent workflow" },
  { fallback: "A Claude Code design plugin and reference set with design red flags and publishing workflows.", focus: "Design guidance / Claude Code" },
  { fallback: "A design capability set around creating systems, importing from Figma and running design experiments.", focus: "Design systems / Figma import" },
  { fallback: "An agent-skill collection for Three.js and graphics work, extending 3D and interactive visual capability.", focus: "Three.js / graphics agents" },
  { fallback: "An open collection of AI-design capabilities and extensions for discovering cross-model design workflows.", focus: "AI design / skill discovery" },
  { fallback: "Creates native editable PPTX files with complete layers and text boxes for dependable handoff.", focus: "Business reports / client proposals / editable delivery" },
  { fallback: "Creates polished zero-dependency HTML presentations that open directly in a browser.", focus: "Online demos / remote talks / interactive presentations" },
  { fallback: "Creates editorial and Swiss-inspired presentation visuals with poster-level finish.", focus: "Product launches / talks / personal branding" },
  { fallback: "Combines detailed HTML motion with editable PPTX export and flexible design specifications.", focus: "Interactive prototypes / design teams / mixed output" },
  { fallback: "Includes countdowns, speaker notes, presenter view and a broad theme system.", focus: "Defenses / roadshows / speaker support" },
  { fallback: "Turns meeting notes or Markdown outlines into structured editable PPTX drafts.", focus: "Fast alignment / quick drafts / outline visualization" },
  { fallback: "Creates visually forceful image-led decks with consistent poster-like art direction.", focus: "Social slices / visual talks / high-impact openings" },
  { fallback: "Rebuilds images, PDFs or image-based PPTX files into editable PPTX through multi-agent visual reconstruction, with optional imagegen and OCR text correction.", focus: "Image to PPT / editable PPTX / OCR correction" },
  { fallback: "Markdown-driven code presentations with syntax highlighting and nested navigation.", focus: "Architecture talks / developer events / open-source demos" }
];

export const skillsTranslations = {
  "footer.learn": { zh: "学习路径", en: "Learn" },
  "footer.vocabulary": { zh: "UI 词典", en: "UI vocabulary" },
  "footer.library": { zh: "案例库", en: "Case library" },
  "skills.heroEyebrow": { zh: "DESIGN SKILL MAP", en: "DESIGN SKILL MAP" },
  "skills.heroDiscover": { zh: "发现", en: "Discover" },
  "skills.heroUnit": { zh: "个", en: "" },
  "skills.heroTitle": { zh: "设计 Skill 能力地图", en: "Design Skill Capability Map" },
  "skills.heroTitleEm": { zh: "找到真正能用的设计 Skill。", en: "Find the design skill that fits." },
  "skills.heroBody": { zh: "这里不是仓库排行榜，而是一张设计能力地图。先选择你要完成的工作，再比较 Skill 的用途、维护状态与调用方式。", en: "This is a map of design capabilities, not a repository leaderboard. Start with the work you need to do, then compare purpose, activity and invocation." },
  "skills.configure": { zh: "配置调用环境", en: "Configure environment" },
  "skills.browse": { zh: "浏览全部 Skills", en: "Browse all Skills" },
  "skills.officialSkill": { zh: "官方设计 Skill", en: "OFFICIAL DESIGN SKILL" },
  "skills.updateCount": { zh: "本次更新", en: "THIS UPDATE" },
  "skills.overview": { zh: "资源概览", en: "Resource overview" },
  "skills.taskPaths": { zh: "任务路径", en: "Task paths" },
  "skills.categories": { zh: "能力分类", en: "Categories" },
  "skills.dataSource": { zh: "数据来源", en: "Data source" },
  "skills.radarLabel": { zh: "当前观察指标", en: "Current directory metrics" },
  "skills.radarSkills": { zh: "收录 Skill", en: "Curated skills" },
  "skills.radarDirections": { zh: "任务路径", en: "Task paths" },
  "skills.radarSource": { zh: "数据来源", en: "Data source" },
  "skills.radarNote": { zh: "持续补充 · 从设计判断到组件落地", en: "Continuously curated · from design judgment to component craft" },
  "skills.repoEyebrow": { zh: "CHOOSE BY TASK", en: "CHOOSE BY TASK" },
  "skills.repoTitle": { zh: "浏览设计 Skills", en: "Browse design Skills" },
  "skills.repoBody": { zh: "先选任务路径，再从结果中挑选合适的 Skill。每个项目都保留仓库入口与一键复制调用命令。", en: "Choose a task path first, then compare the relevant skills. Every item keeps its repository link and one-click invocation command." },
  "skills.repoToolbarLabel": { zh: "Skill 筛选工具", en: "Skill directory filters" },
  "skills.repoSearch": { zh: "搜索名称、用途或仓库", en: "Search name, purpose or repository" },
  "skills.filters": { zh: "分类筛选", en: "Categories" },
  "skills.taskRailLabel": { zh: "按任务探索", en: "Explore by task" },
  "skills.directoryModeLabel": { zh: "浏览类型", en: "Browse type" },
  "skills.sortCurated": { zh: "精选", en: "Curated" },
  "skills.sortStars": { zh: "Stars", en: "Stars" },
  "skills.sortUpdated": { zh: "最近更新", en: "Latest" },
  "skills.clearFilters": { zh: "重置", en: "Reset" },
  "skills.columnNumber": { zh: "编号", en: "No." },
  "skills.columnCategory": { zh: "分类", en: "Category" },
  "skills.columnSkill": { zh: "Skill / 用途", en: "Skill / purpose" },
  "skills.columnBestFor": { zh: "适合", en: "Best for" },
  "skills.columnStats": { zh: "热度", en: "Activity" },
  "skills.columnAction": { zh: "调用", en: "Use" }
};

export const categoryGroups = [
  { key: "creative", zh: "体验创作", en: "Experience & craft", categories: ["DESIGN", "UX", "MOTION", "VIDEO", "A11Y"] },
  { key: "build", zh: "构建系统", en: "Build & systems", categories: ["FRONTEND", "SYSTEM", "ENGINEERING", "3D"] },
  { key: "agent", zh: "Agent 协作", en: "Agent workflows", categories: ["AI DESIGN", "REVIEW", "DIRECTORY"] },
  { key: "presentation", zh: "演示与汇报", en: "Presentation", categories: ["PRESENTATION"] }
];

export const categoryLabels = {
  DESIGN: { zh: "界面设计", en: "Interface design" },
  UX: { zh: "用户体验", en: "User experience" },
  MOTION: { zh: "动效", en: "Motion" },
  VIDEO: { zh: "视频创作", en: "Video" },
  A11Y: { zh: "无障碍", en: "Accessibility" },
  FRONTEND: { zh: "前端构建", en: "Frontend" },
  SYSTEM: { zh: "设计系统", en: "Design systems" },
  ENGINEERING: { zh: "工程工作流", en: "Engineering" },
  "3D": { zh: "3D / 图形", en: "3D / graphics" },
  "AI DESIGN": { zh: "AI 设计", en: "AI design" },
  REVIEW: { zh: "设计评审", en: "Design review" },
  DIRECTORY: { zh: "资源发现", en: "Discovery" },
  PRESENTATION: { zh: "演示 / PPT", en: "Presentation / PPT" }
};

export const categoryVisuals = {
  VIDEO: { zh: "导演下一幕", en: "Direct the\nnext scene" },
  DESIGN: { zh: "从意图到\n界面", en: "From intent\nto interface" },
  MOTION: { zh: "让动效\n有目的", en: "Motion has\na purpose" },
  ENGINEERING: { zh: "更有把握地\n交付", en: "Ship with\nconfidence" },
  FRONTEND: { zh: "为真实使用\n而构建", en: "Build for\nreal use" },
  UX: { zh: "让路径\n更清晰", en: "Make paths\nclear" },
  A11Y: { zh: "默认\n无障碍", en: "Accessible\nby default" },
  SYSTEM: { zh: "让每个部分\n保持一致", en: "Keep every\npiece coherent" },
  "3D": { zh: "增加一个\n新维度", en: "Add a new\ndimension" },
  "AI DESIGN": { zh: "从提示到\n产品", en: "Prompt to\nproduct" },
  DIRECTORY: { zh: "找到真正\n适合的", en: "Find what\nfits" },
  REVIEW: { zh: "看见还\n缺少什么", en: "See what\nis missing" },
  PRESENTATION: { zh: "把内容变成\n一场演示", en: "Turn content into\na presentation" }
};

export const skillVisuals = {
  "Vincentwei1021/video-shotcraft": { zh: "把镜头写成\n可复用配方", en: "Turn shots into\nreusable recipes" },
  "emilkowalski/skills": { zh: "让界面细节\n更自然", en: "Make interface\ndetails feel natural" },
  "pbakaus/impeccable": { zh: "提升界面的\n完成度", en: "Raise the level\nof interface polish" },
  "greensock/GSAP": { zh: "让动效流畅\n且有节奏", en: "Make motion fluid\nand intentional" },
  "Leonxlnx/taste-skill": { zh: "摆脱模板化\n设计", en: "Move beyond\ntemplated design" },
  "mattpocock/skills": { zh: "把工程经验\n变成工作流", en: "Turn engineering\npractice into workflows" },
  "anthropics/skills": { zh: "从需求构建\n真实界面", en: "Build real interfaces\nfrom requirements" },
  "vercel-labs/agent-skills": { zh: "按生产标准\n构建前端", en: "Build frontend work\nto production standards" },
  "nexu-io/open-design": { zh: "把提示变成\n设计工作台", en: "Turn prompts into\na design workspace" },
  "vercel-labs/design-systems-to-agent-skills": { zh: "把设计系统\n转成 Skill", en: "Turn design systems\ninto agent skills" },
  "Subhan-code/Amicro--Micro-transitions-": { zh: "微交互与\n转场动画", en: "Micro interactions\nand transitions" },
  "weareoxd/design-skill-generator": { zh: "把参考图变成\n设计 Skill", en: "Turn references\ninto design skills" },
  "nolly-studio/agent-skills": { zh: "沉淀项目级\n设计契约", en: "Capture project-level\ndesign contracts" },
  "nextlevelbuilder/ui-ux-pro-max-skill": { zh: "把复杂数据\n变成交互演示", en: "Turn complex data into\nan interactive presentation" },
  "motiondivision/motion": { zh: "为交互增加\n自然反馈", en: "Add natural feedback\nto interactions" },
  "radix-ui/primitives": { zh: "从无障碍原语\n开始构建", en: "Start with accessible\ninterface primitives" },
  "shadcn-ui/ui": { zh: "复制高质量\n组件系统", en: "Copy a polished\ncomponent system" },
  "wshobson/agents-tailwind-design-system": { zh: "用 Tailwind v4\n沉淀设计系统", en: "Shape Tailwind v4\ninto a design system" },
  "tailwindlabs/headlessui": { zh: "组合可靠的\n交互模式", en: "Compose dependable\ninteraction patterns" },
  "twostraws/SwiftUI-Agent-Skill": { zh: "让 Agent 写出\n现代 SwiftUI", en: "Help agents write\nmodern SwiftUI" },
  "lucide-icons/lucide": { zh: "统一产品的\n图标语言", en: "Unify the product's\nicon language" },
  "pmndrs/react-three-fiber": { zh: "把 3D 带进\nReact", en: "Bring 3D into\nReact" },
  "ahujasid/blender-mcp": { zh: "让 Agent 控制\nBlender 场景", en: "Let agents control\nBlender scenes" },
  "storybookjs/storybook": { zh: "让组件可见\n可测可协作", en: "Make components visible,\ntestable and collaborative" },
  "google-labs-code/stitch-skills": { zh: "从提示生成\n可迭代界面", en: "Generate interfaces\nready to iterate" },
  "figma/mcp-server-guide": { zh: "把 Figma 接入\nAgent 工具", en: "Connect Figma\nto agent tools" },
  "bergside/awesome-design-skills": { zh: "快速找到合适的\n设计能力", en: "Find the right\ndesign capability faster" },
  "gztchan/awesome-design": { zh: "把设计资源\n收进工具箱", en: "Put design resources\ninto your toolkit" },
  "magnus919/agent-skills": { zh: "把产品路径\n设计清楚", en: "Make product paths\nclearer" },
  "sergekostenchuk/ui-ux-agent-skill-system": { zh: "补齐真实产品\n界面状态", en: "Cover real product\ninterface states" },
  "content-designer/ux-writing-skill": { zh: "让界面文案\n更清楚", en: "Make interface copy\nclearer" },
  "Community-Access/accessibility-agents": { zh: "交付前完成\n无障碍审查", en: "Audit accessibility\nbefore shipping" },
  "skydashnet/material-design-3-ui-skill": { zh: "按 Material 3\n建立界面", en: "Design with\nMaterial 3" },
  "wenkang-deepblue/frontend-design": { zh: "把设计微调\n交回 Agent", en: "Send design tweaks\nback to agents" },
  "SeanJ1ang/design-judge-skills": { zh: "看见界面还\n缺少什么", en: "See what the interface\nis still missing" },
  "ConardLi/garden-skills": { zh: "组合 AI 产品\n开发能力", en: "Combine capabilities\nfor AI product work" },
  "Owl-Listener/designer-skills": { zh: "辅助日常的\n设计决策", en: "Support everyday\ndesign decisions" },
  "superdesigndev/superdesign-skill": { zh: "连接设计思考\n与前端落地", en: "Connect design thinking\nto frontend execution" },
  "mistyhx/frontend-design-audit": { zh: "系统审查\n前端页面", en: "Audit frontend pages\nsystematically" },
  "plugin87/ux-ui-agent-skills": { zh: "覆盖完整的\nUX/UI 工作流", en: "Cover the complete\nUX/UI workflow" },
  "ZeroZ-lab/cc-design": { zh: "提前识别\n设计红旗", en: "Spot design red flags\nearly" },
  "JimLiu/baoyu-design": { zh: "建立可复用的\n设计系统", en: "Build a reusable\ndesign system" },
  "scottstts/Threejs-Awesome-Graphics-Agent-Skills": { zh: "增加一个互动\n新维度", en: "Add a new dimension\nof interaction" },
  "Owl-Listener/ai-design-skills": { zh: "发现跨模型的\n设计工作流", en: "Discover cross-model\ndesign workflows" },
  "hugohe3/ppt-master": { zh: "交付真正可编辑的\n原生 PPTX", en: "Deliver a truly editable\nnative PPTX" },
  "zarazhangrui/frontend-slides": { zh: "双击浏览器就能\n开始演示", en: "Open the browser and\nstart presenting" },
  "op7418/guizang-ppt-skill": { zh: "让演示拥有\n杂志级审美", en: "Give presentations\neditorial-level craft" },
  "alchaincyf/huashu-design": { zh: "同时拥有动效与\n可编辑交付", en: "Combine motion with\neditable delivery" },
  "lewislulu/html-ppt-skill": { zh: "把 HTML 变成\n演示舞台", en: "Turn HTML into\na presentation stage" },
  "MiniMax-AI/skills": { zh: "把会议大纲快速\n变成 PPT 草稿", en: "Turn meeting outlines\ninto PPT drafts" },
  "ningzimu/codex-ppt": { zh: "用海报级画面\n制造视觉冲击", en: "Create visual impact\nwith poster-like slides" },
  "ningzimu/image-to-editable-ppt-skill": { zh: "把图片重建成\n可编辑 PPT", en: "Rebuild images into\neditable decks" },
  "ryanbbrown/revealjs-skill": { zh: "用代码和 Markdown\n讲清技术方案", en: "Explain technical ideas\nwith code and Markdown" }
};

export const skillOfficialPages = {
  "greensock/GSAP": "https://gsap.com",
  "motiondivision/motion": "https://motion.dev",
  "radix-ui/primitives": "https://www.radix-ui.com/primitives",
  "shadcn-ui/ui": "https://github.com/shadcn-ui/ui",
  "wshobson/agents-tailwind-design-system": "https://github.com/wshobson/agents/tree/main/plugins/frontend-mobile-development/skills/tailwind-design-system",
  "tailwindlabs/headlessui": "https://github.com/tailwindlabs/headlessui",
  "twostraws/SwiftUI-Agent-Skill": "https://github.com/twostraws/SwiftUI-Agent-Skill",
  "gztchan/awesome-design": "https://github.com/gztchan/awesome-design",
  "nexu-io/open-design": "https://github.com/nexu-io/open-design",
  "vercel-labs/design-systems-to-agent-skills": "https://github.com/vercel-labs/design-systems-to-agent-skills",
  "Subhan-code/Amicro--Micro-transitions-": "https://github.com/Subhan-code/Amicro--Micro-transitions-",
  "lewislulu/html-ppt-skill": "https://github.com/lewislulu/html-ppt-skill",
  "weareoxd/design-skill-generator": "https://github.com/weareoxd/design-skill-generator",
  "figma/mcp-server-guide": "https://www.figma.com/mcp-catalog/",
  "nolly-studio/agent-skills": "https://github.com/nolly-studio/agent-skills",
  "magnus919/agent-skills": "https://github.com/magnus919/agent-skills",
  "sergekostenchuk/ui-ux-agent-skill-system": "https://github.com/sergekostenchuk/ui-ux-agent-skill-system",
  "content-designer/ux-writing-skill": "https://github.com/content-designer/ux-writing-skill",
  "Community-Access/accessibility-agents": "https://github.com/Community-Access/accessibility-agents",
  "skydashnet/material-design-3-ui-skill": "https://github.com/skydashnet/material-design-3-ui-skill",
  "wenkang-deepblue/frontend-design": "https://github.com/wenkang-deepblue/frontend-design",
  "ningzimu/image-to-editable-ppt-skill": "https://github.com/ningzimu/image-to-editable-ppt-skill",
  "lucide-icons/lucide": "https://lucide.dev/icons",
  "ahujasid/blender-mcp": "https://github.com/ahujasid/blender-mcp",
  "pmndrs/react-three-fiber": "https://r3f.docs.pmnd.rs/getting-started/introduction",
  "storybookjs/storybook": "https://storybook.js.org"
};
