#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import {
  getLibraryPreviewProfile,
  libraryPreviewCaseIds,
  standardCanonicalPreview,
  standardPreviewDevice,
} from "../library-preview-config.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const catalogDir = path.join(root, "catalog");
const casesDir = path.join(catalogDir, "cases");
const stylesDir = path.join(catalogDir, "styles");
const brandsDir = path.join(catalogDir, "brands");
const componentsDir = path.join(catalogDir, "components");
const outputPath = path.join(catalogDir, "index.js");
const legacyPath = path.join(root, "library.js");
const importLegacy = process.argv.includes("--import-legacy");
const checkOnly = process.argv.includes("--check");
const localizedCaseKeys = ["style", "reference", "prompt", "summary", "bestFor", "tags", "palette", "layout", "recipe"];
const localizedRecipeKeys = ["principle", "image", "type", "components", "motion", "avoid"];
const localizedStyleKeys = ["name", "sourceStatus", "industry", "styles", "completeness", "foundations", "components", "visualLanguage", "contentVoice", "accessibility", "dos", "donts"];
const localizedComponentKeys = ["sourceStatus", "category", "summary", "anatomy", "states", "behavior", "accessibility", "do", "dont"];

if (importLegacy) importLegacyCases();

const cases = readCollection(casesDir, "case");
const styles = readCollection(stylesDir, "style profile");
const brands = readCollection(brandsDir, "brand profile");
const components = readCollection(componentsDir, "component reference");
validate(cases, styles, brands, components);

const generated = `${[
  "// Generated by scripts/build_catalog.mjs. Do not edit directly.",
  `export const styleGuides = ${JSON.stringify(cases, null, 2)};`,
  `export const styleProfiles = ${JSON.stringify(styles, null, 2)};`,
  `export const brandProfiles = ${JSON.stringify(brands, null, 2)};`,
  `export const componentReferences = ${JSON.stringify(components, null, 2)};`,
  "",
].join("\n")}`;

if (checkOnly) {
  if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, "utf8") !== generated) throw new Error("catalog/index.js is stale. Run npm run build:catalog.");
} else {
  fs.writeFileSync(outputPath, generated, "utf8");
}

console.log(JSON.stringify({ cases: cases.length, styles: styles.length, brands: brands.length, components: components.length, output: path.relative(root, outputPath) }, null, 2));

function importLegacyCases() {
  if (fs.existsSync(casesDir) && fs.readdirSync(casesDir).some((file) => file.endsWith(".json"))) return;
  const source = fs.readFileSync(legacyPath, "utf8");
  const start = source.indexOf("const styleGuides = [");
  const end = source.indexOf("const previewImageSets", start);
  if (start < 0 || end < 0) throw new Error("Could not locate legacy styleGuides data.");
  const context = {};
  vm.createContext(context);
  vm.runInContext(source.slice(start, end).replace("const styleGuides", "globalThis.styleGuides"), context);
  fs.mkdirSync(casesDir, { recursive: true });
  for (const item of context.styleGuides) {
    item.styleProfileIds = inferStyleProfiles(item);
    fs.writeFileSync(path.join(casesDir, `${item.id}.json`), `${JSON.stringify(item, null, 2)}\n`, "utf8");
  }
}

function inferStyleProfiles(item) {
  if (["fashion", "organique", "carry-bag", "still-form", "relay-music"].includes(item.id)) return ["editorial-commerce"];
  if (["cleanbite", "signal-grid", "volt-route", "fithub"].includes(item.id)) return ["minimal-tech"];
  return ["soft-lifestyle"];
}

function readCollection(dir, label) {
  if (!fs.existsSync(dir)) throw new Error(`Missing ${label} directory: ${path.relative(root, dir)}`);
  return fs.readdirSync(dir).filter((file) => file.endsWith(".json")).sort().map((file) => JSON.parse(fs.readFileSync(path.join(dir, file), "utf8")));
}

function validate(cases, styles, brands, components) {
  assertUnique(cases, "Case");
  assertUnique(styles, "Style profile");
  assertUnique(brands, "Brand profile");
  assertUnique(components, "Component reference");

  const styleIds = new Set(styles.map((item) => item.id));
  const brandIds = new Set(brands.map((item) => item.id));
  const componentIds = new Set(components.map((item) => item.id));
  const caseIds = new Set(cases.map((item) => item.id));
  const previewIds = new Set(libraryPreviewCaseIds);

  if (caseIds.size !== previewIds.size || [...caseIds].some((id) => !previewIds.has(id))) {
    throw new Error(`Preview contract coverage must match the case catalog exactly. Catalog=${[...caseIds].sort().join(",")} Preview=${[...previewIds].sort().join(",")}`);
  }

  for (const item of cases) {
    requireKeys(item, ["id", "name", "style", "category", "referenceImage", "prompt", "summary", "bestFor", "preview"], "Case");
    if (!Array.isArray(item.tags) || item.tags.length === 0) throw new Error(`Case ${item.id} requires tags.`);
    if (!Array.isArray(item.styleProfileIds) || item.styleProfileIds.length === 0) throw new Error(`Case ${item.id} requires styleProfileIds.`);
    requireKeys(item.locales?.en || {}, localizedCaseKeys, `Case ${item.id} locales.en`);
    requireKeys(item.locales.en.recipe, localizedRecipeKeys, `Case ${item.id} locales.en.recipe`);
    if (!Array.isArray(item.locales.en.tags) || item.locales.en.tags.length !== item.tags.length) throw new Error(`Case ${item.id} locales.en.tags must map one-to-one to the default tags.`);
    for (const id of item.styleProfileIds) if (!styleIds.has(id)) throw new Error(`Case ${item.id} references unknown style profile ${id}.`);

    const preview = getLibraryPreviewProfile(item.id);
    if (!preview) throw new Error(`Case ${item.id} is missing a preview contract.`);
    if (preview.frameOwner !== "library") throw new Error(`Case ${item.id} must use the Library-owned device frame.`);
    if (preview.allowBakedDevice !== false) throw new Error(`Case ${item.id} must reject baked device chrome.`);
    if (preview.screen.width !== standardPreviewDevice.width || preview.screen.height !== standardPreviewDevice.height) {
      throw new Error(`Case ${item.id} must render a ${standardPreviewDevice.width}x${standardPreviewDevice.height} source screen.`);
    }
    if (preview.canonical.width !== standardCanonicalPreview.width || preview.canonical.height !== standardCanonicalPreview.height) {
      throw new Error(`Case ${item.id} must use ${standardCanonicalPreview.width}x${standardCanonicalPreview.height} canonical previews.`);
    }
  }

  for (const style of styles) {
    requireKeys(style, ["id", "name", "sourceType", "sourceStatus", "reviewedAt", "platforms", "industry", "styles", "completeness", "foundations", "components", "visualLanguage", "contentVoice", "accessibility", "dos", "donts"], "Style profile");
    requireKeys(style.locales?.en || {}, localizedStyleKeys, `Style profile ${style.id} locales.en`);
    if (style.sourceType !== "style-reference" || style.sourceStatus !== "风格参考") throw new Error(`Style profile ${style.id} has invalid provenance.`);
    assertDate(style.reviewedAt, `Style profile ${style.id}`);
  }

  for (const brand of brands) {
    requireKeys(brand, ["id", "name", "organization", "sourceType", "sourceStatus", "sourceUrl", "reviewedAt", "platforms", "description", "componentReferenceIds", "disclaimer"], "Brand profile");
    requireKeys(brand.locales?.en || {}, ["sourceStatus", "description", "disclaimer"], `Brand profile ${brand.id} locales.en`);
    if (!["品牌提供", "基于公开设计规范", "自定义品牌"].includes(brand.sourceStatus)) throw new Error(`Brand ${brand.id} has an invalid sourceStatus.`);
    assertDate(brand.reviewedAt, `Brand ${brand.id}`);
    if (!Array.isArray(brand.componentReferenceIds) || brand.componentReferenceIds.length === 0) throw new Error(`Brand ${brand.id} requires componentReferenceIds.`);
  }

  for (const component of components) {
    requireKeys(component, ["id", "name", "brandProfileId", "sourceType", "sourceStatus", "sourceUrl", "reviewedAt", "platforms", "category", "summary", "anatomy", "states", "behavior", "accessibility", "tokens"], "Component reference");
    requireKeys(component.locales?.en || {}, localizedComponentKeys, `Component ${component.id} locales.en`);
    if (!brandIds.has(component.brandProfileId)) throw new Error(`Component ${component.id} references unknown brand profile ${component.brandProfileId}.`);
    if (component.sourceStatus !== "基于公开设计规范") throw new Error(`Component ${component.id} has invalid provenance.`);
    assertDate(component.reviewedAt, `Component ${component.id}`);
  }

  for (const brand of brands) for (const id of brand.componentReferenceIds) {
    if (!componentIds.has(id)) throw new Error(`Brand ${brand.id} references unknown component ${id}.`);
    const component = components.find((item) => item.id === id);
    if (component.brandProfileId !== brand.id) throw new Error(`Component ${id} does not belong to brand ${brand.id}.`);
  }
}

function assertUnique(items, label) {
  const ids = new Set(items.map((item) => item.id));
  if (ids.size !== items.length) throw new Error(`${label} ids must be unique.`);
}

function requireKeys(item, keys, label) {
  for (const key of keys) if (item[key] === undefined || item[key] === null || item[key] === "") throw new Error(`${label} ${item.id || "(unknown)"} is missing ${key}.`);
}

function assertDate(value, label) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new Error(`${label} has an invalid reviewedAt date.`);
}
