#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  libraryPreviewCaseIds,
  standardCanonicalPreview,
  standardPreviewDevice,
} from "../src/features/library/library-preview-config.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const catalogDir = path.join(root, "catalog");
const readCollection = (name) => fs.readdirSync(path.join(catalogDir, name))
  .filter((file) => file.endsWith(".json"))
  .sort()
  .map((file) => JSON.parse(fs.readFileSync(path.join(catalogDir, name, file), "utf8")));

const styleGuides = readCollection("cases");
const styleProfiles = readCollection("styles");
const brandProfiles = readCollection("brands");
const componentReferences = readCollection("components");

for (const [label, items] of [["case", styleGuides], ["style", styleProfiles], ["brand", brandProfiles], ["component", componentReferences]]) {
  const ids = items.map((item) => item.id);
  if (ids.some((id) => !id) || new Set(ids).size !== ids.length) throw new Error(`${label} ids must be present and unique`);
}

const caseIds = new Set(styleGuides.map((item) => item.id));
const previewIds = new Set(libraryPreviewCaseIds);
if (caseIds.size !== previewIds.size || [...caseIds].some((id) => !previewIds.has(id))) {
  throw new Error("Library preview contract must cover the case catalog exactly.");
}
if (standardPreviewDevice.width !== 390 || standardPreviewDevice.height !== 844 || standardCanonicalPreview.width !== 780 || standardCanonicalPreview.height !== 1688) {
  throw new Error("Unexpected Library preview geometry.");
}

const output = `${[
  "// Generated by scripts/build_catalog.mjs. Do not edit directly.",
  `export const styleGuides = ${JSON.stringify(styleGuides, null, 2)};`,
  `export const styleProfiles = ${JSON.stringify(styleProfiles, null, 2)};`,
  `export const brandProfiles = ${JSON.stringify(brandProfiles, null, 2)};`,
  `export const componentReferences = ${JSON.stringify(componentReferences, null, 2)};`,
  "",
].join("\n")}`;
const outputPath = path.join(catalogDir, "index.js");

if (process.argv.includes("--check")) {
  if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, "utf8") !== output) throw new Error("catalog/index.js is stale. Run npm run build:catalog.");
} else {
  fs.writeFileSync(outputPath, output, "utf8");
}

console.log(`Catalog ready: ${styleGuides.length} cases, ${styleProfiles.length} styles, ${brandProfiles.length} brands, ${componentReferences.length} components.`);
