#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const catalogDir = path.join(root, "catalog");
const casesDir = path.join(catalogDir, "cases");
const brandsDir = path.join(catalogDir, "brands");
const outputPath = path.join(catalogDir, "index.js");
const legacyPath = path.join(root, "library.js");
const importLegacy = process.argv.includes("--import-legacy");
const checkOnly = process.argv.includes("--check");

if (importLegacy) importLegacyCases();

const cases = readCollection(casesDir, "case");
const brands = readCollection(brandsDir, "brand profile");
validate(cases, brands);

const generated = `${["// Generated by scripts/build_catalog.mjs. Do not edit directly.", `export const styleGuides = ${JSON.stringify(cases, null, 2)};`, `export const brandProfiles = ${JSON.stringify(brands, null, 2)};`, ""].join("\n")}`;
if (checkOnly) {
  if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, "utf8") !== generated) {
    throw new Error("catalog/index.js is stale. Run npm run catalog:build.");
  }
} else {
  fs.writeFileSync(outputPath, generated, "utf8");
}
console.log(JSON.stringify({ cases: cases.length, brands: brands.length, output: path.relative(root, outputPath) }, null, 2));

function importLegacyCases() {
  if (fs.existsSync(casesDir) && fs.readdirSync(casesDir).some((file) => file.endsWith(".json"))) return;
  const source = fs.readFileSync(legacyPath, "utf8");
  const start = source.indexOf("const styleGuides = [");
  const end = source.indexOf("const previewImageSets", start);
  if (start < 0 || end < 0) throw new Error("Could not locate legacy styleGuides data.");
  const context = {};
  vm.createContext(context);
  vm.runInContext(source.slice(start, end).replace("const styleGuides", "globalThis.styleGuides"), context);
  fs.mkdirSync(casesDir, { recursive: true });
  for (const item of context.styleGuides) {
    item.brandProfileIds = inferBrandProfiles(item);
    fs.writeFileSync(path.join(casesDir, `${item.id}.json`), `${JSON.stringify(item, null, 2)}\n`, "utf8");
  }
}

function inferBrandProfiles(item) {
  if (["fashion", "organique", "carry-bag", "still-form", "relay-music"].includes(item.id)) return ["editorial-commerce"];
  if (["cleanbite", "signal-grid", "volt-route", "fithub"].includes(item.id)) return ["minimal-tech"];
  return ["soft-lifestyle"];
}

function readCollection(dir, label) {
  if (!fs.existsSync(dir)) throw new Error(`Missing ${label} directory: ${path.relative(root, dir)}`);
  return fs.readdirSync(dir)
    .filter((file) => file.endsWith(".json"))
    .sort()
    .map((file) => JSON.parse(fs.readFileSync(path.join(dir, file), "utf8")));
}

function validate(cases, brands) {
  const ids = new Set();
  for (const item of cases) {
    for (const key of ["id", "name", "style", "category", "referenceImage", "prompt", "summary", "bestFor", "preview"]) {
      if (!item[key]) throw new Error(`Case ${item.id || "(unknown)"} is missing ${key}.`);
    }
    if (ids.has(item.id)) throw new Error(`Duplicate case id: ${item.id}`);
    ids.add(item.id);
    if (!Array.isArray(item.tags) || item.tags.length === 0) throw new Error(`Case ${item.id} requires tags.`);
    if (!Array.isArray(item.brandProfileIds) || item.brandProfileIds.length === 0) throw new Error(`Case ${item.id} requires brandProfileIds.`);
  }
  const brandIds = new Set(brands.map((item) => item.id));
  if (brandIds.size !== brands.length) throw new Error("Brand profile ids must be unique.");
  for (const brand of brands) {
    for (const key of ["id", "name", "sourceType", "sourceStatus", "reviewedAt", "platforms", "industry", "styles", "completeness", "foundations", "components", "visualLanguage", "contentVoice", "accessibility", "dos", "donts"]) {
      if (!brand[key]) throw new Error(`Brand ${brand.id || "(unknown)"} is missing ${key}.`);
    }
    if (!/^\d{4}-\d{2}-\d{2}$/.test(brand.reviewedAt)) throw new Error(`Brand ${brand.id} has an invalid reviewedAt date.`);
    if (!["品牌提供", "基于公开设计规范", "风格参考", "自定义品牌"].includes(brand.sourceStatus)) throw new Error(`Brand ${brand.id} has an invalid sourceStatus.`);
    for (const key of ["colors", "typography", "spacing", "radius", "elevation", "grid", "motion"]) {
      if (!brand.foundations[key]) throw new Error(`Brand ${brand.id} foundations is missing ${key}.`);
    }
    for (const key of ["button", "card", "navigation", "form", "dialog"]) {
      if (!brand.components[key]) throw new Error(`Brand ${brand.id} components is missing ${key}.`);
    }
    for (const key of ["photography", "illustration", "iconography"]) {
      if (!brand.visualLanguage[key]) throw new Error(`Brand ${brand.id} visualLanguage is missing ${key}.`);
    }
    if (!Array.isArray(brand.dos) || !Array.isArray(brand.donts)) throw new Error(`Brand ${brand.id} dos and donts must be arrays.`);
  }
  for (const item of cases) {
    for (const brandId of item.brandProfileIds) {
      if (!brandIds.has(brandId)) throw new Error(`Case ${item.id} references unknown brand profile ${brandId}.`);
    }
  }
}
